<?php
$this->headTitle('Shop Data- Edit Data');

$form = $this->form;
//
$form->setElementDecorators(array('ViewHelper'));
?>

<div class="page-header">
    <h1>Members <small>Edit Data</small></h1>
</div>

<div class="row">
    <div class="col-lg-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages); ?>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right" >
                <div class="btn-group" role="group" aria-label="...">
                    <a  href="<?php echo $this->url(array('controller' => 'admin_shopdata', 'action' => 'index',), 'default', true); ?>" type="button" 
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-arrow-left"></i>Back to shop data</a>

                </div>  
            </div>
            <div class="panel-body">

                <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                    
                    <input type="hidden" name="task" value="update">

                    <fieldset>

                        <!-- Form Name -->
                        <legend>Edit Data</legend>

                            <!-- Text input-->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="address">Address</label>  
                                <div class="col-md-4">
                                    <?php
                                    echo $form->getElement('address')->setAttribs(array(
                                        'class' => 'form-control input-md',
                                        'placeholder' => "enter address",
                                        'id' => 'address',
                                    ));
                                    ?>

                                    <span class="help-block">min 3 max 25 characters</span>  
                                </div>

                                <div class="col-md-4">
                                    <?php if ($form->getElement('address')->hasErrors()) { ?>
                                        <div class="has-error">
                                            <?php foreach ($form->getElement('address')->getMessages() as $message) { ?>
                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>

                            </div>
                            
                            <div class="form-group">
                             
                            <label class="col-md-4 control-label" for="city">City</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('city')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter city',
                                    'id' => 'city',
                                ));
                                ?>

                                
                                <span class="help-block">min 3 max 25 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('city')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('city')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                            </div>
                        </div>


                            <!-- Text input-->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="phone">Phone</label>  
                                <div class="col-md-4">
                                    <?php
                                    echo $form->getElement('phone')->setAttribs(array(
                                        'class' => 'form-control input-md',
                                        'placeholder' => 'enter phone',
                                        'id' => 'phone',
                                    ));
                                    ?>


                                    <span class="help-block">min 3 max 25 characters</span>  
                                </div>
                                <div class="col-md-4">
                                    <?php if ($form->getElement('phone')->hasErrors()) { ?>
                                        <div class="has-error">
                                            <?php foreach ($form->getElement('phone')->getMessages() as $message) { ?>
                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>

                                </div>
                            </div>

                            <!-- Text input-->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="email">Email</label>  
                                <div class="col-md-4">

                                    <?php
                                    echo $form->getElement('email')->setAttribs(array(
                                        'class' => 'form-control input-md',
                                        'placeholder' => 'enter m email',
                                        'id' => 'email',
                                    ));
                                    ?>

                                    <span class="help-block">username@domain</span>  
                                </div>
                                <div class="col-md-4">
                                    <?php if ($form->getElement('email')->hasErrors()) { ?>
                                        <div class="has-error">
                                            <?php foreach ($form->getElement('email')->getMessages() as $message) { ?>
                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>


                                </div>
                            </div>

                            

                            <!-- Textarea -->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="about_us">About Us</label>
                                <div class="col-md-4"> 

                                    <?php
                                    echo $form->getElement('about_us')->setAttribs(array(
                                        'class' => 'form-control',
                                        'id' => 'about_us',
                                        'rows' => 3
                                    ));
                                    ?>

                                </div>
                                <div class="col-md-4">
                                    <?php if ($form->getElement('about_us')->hasErrors()) { ?>
                                        <div class="has-error">
                                            <?php foreach ($form->getElement('about_us')->getMessages() as $message) { ?>
                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                            
                       
                            
                             <div class="form-group">
                            <label class="col-md-4 control-label" for="twitter">Twitter</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('twitter')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter twitter link',
                                    'id' => 'twitter',
                                ));
                                ?>

                                
                                <span class="help-block">min 3 max 25 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('twitter')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('twitter')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="facebook">Facebook</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('facebook')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter facebook link',
                                    'id' => 'facebook',
                                ));
                                ?>

                                
                                <span class="help-block">min 3 max 25 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('facebook')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('facebook')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="google_plus">Google Plus</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('google_plus')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter google_plus link',
                                    'id' => 'google_plus',
                                ));
                                ?>

                                
                                <span class="help-block">min 3 max 25 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('google_plus')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('google_plus')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="linkedin">Linkedin</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('linkedin')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter linkedin link',
                                    'id' => 'linkedin',
                                ));
                                ?>

                                
                                <span class="help-block">min 3 max 25 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('linkedin')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('linkedin')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                            </div>
                        </div>
                        
                              <!-- Image -->
                        
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="logo_photo">Photo</label>
                            <div class="col-md-4"> 
                                <div>
                                    <a href="#" class="thumbnail">
                                        <img src="<?php echo $this->logoImgUrl($this->logo);?>">
                                    </a>
                                    
                                </div>
                                <input type="file" name="logo_photo" id="logo_photo" class="form-control  input-md">
                                <span class="help-block">Change Photo</span>
                                
                            </div>
                            <div class="col-md-4">
                                 <?php if ($form->getElement('logo_photo')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('logo_photo')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                            
                            
                            <!-- Button (Double) -->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="new_data_cancel"></label>
                                <div class="col-md-4 text-right">
                                    <a 
                                        href ="<?php echo $this->url(array('controller'=> 'admin_shopdata', 'action'=> 'index'), 'default', true)?>"
                                        id="new_data_cancel" name="new_data_cancel" class="btn btn-default">Cancel</a>
                                    <button type="submit" id="new_data_submit" name="new_data_submit" class="btn btn-success">Save</button>
                                </div>

                            </div>



                        </fieldset>
                </form>

            </div>
        </div>
    </div>
</div>

