
<?php
$this->headTitle('Shop Data');

$informations = $this->informations;
//$informations=array();

?>


<div class="page-header">

    <div class="row">
        <div class="col-lg-12">
            <?php echo $this->systemMessagesHtml($this->systemMessages); ?>
        </div>
    </div>

    <h1>Shop Data</h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right" >
                <div class="btn-group" role="group" aria-label="...">
                   <?php if(empty($informations)) {?>
                    <a  href="<?php echo $this->url(array('controller' => 'admin_shopdata', 'action' => 'add'), 'default', true); ?>" type="button" 
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-plus"></i>Add Data</a>
                       <?php }?>
                </div>  
            </div>
           
            <div class="panel-body">

                <table id="rows-table" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            
                            <th class="text-center">About Us</th>
                            <th class="text-center">Address</th>
                            <th class="text-center">Email</th>
                            <th class="text-center">Phone</th>
                            <th class="text-center">#</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($informations as $data) {?>
                                <tr>
                                    <td class="text-center"><?php echo $this->escape($data['about_us']); ?></td>
                                    <td class="text-center"><?php echo $this->escape($data['address']); ?></td>
                                    <td class="text-center"><?php echo $this->escape($data['email']); ?></td>
                                    <td class="text-center"><?php echo $this->escape($data['phone']); ?></td>
                                    <td class="text-center">
                                        <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                          
                                            <a 
                                                href="<?php echo $this->url(array('controller' => 'admin_shopdata', 'action' => 'edit','id' => $data['id']), 'default', true); ?>"
                                                type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                            
                                        </div>
                                    </td>
                                </tr>
                                <?php
                            } 
                                ?>
                                
                        
                    </tbody>
                </table>



            </div>
        </div>
    </div>
</div>



<?php
//dodatni css na nasu stranicu
$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.css'));

$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.js'));
?>


<!--
<script>
<?php $this->inlineScript()->captureStart(); ?>

    $('#rows-table').on('click', '[data-action="delete"]', function (e) {
        e.preventDefault();
        e.stopPropagation();


        //calculate target element
        var target = $(this).is('[data-action="delete"]') ? $(this) : $(this).closest('[data-action="delete"]');


        //verzija preko attr fje
        //var memberId = target.attr('data-member-id'); //ovde pun naziv sa data

        //verzija preko datat fje
        var memberId = target.data('member-id');//ovde ime bez data


        //var memberName = target.attr('data-member-id');
        //alert(memberId);
        //set value for input field with name "id"


        $('#delete-warning-dialog').find('[name="id"]').val(memberId);

        $('#delete-warning-dialog').modal('show');


        var memberData = target.attr('data-memberName');
        $('.osoba').text(memberData);


    });

    $('#rows-table').on('click', '[data-action="disable"]', function (e) {
        e.preventDefault();
        e.stopPropagation();


        //calculate target element
        var target = $(this).is('[data-action="disable"]') ? $(this) : $(this).closest('[data-action="disable"]');

        var memberId = target.attr('data-member-id');

        //verzija preko datat fje
        //var memberId =target.data('memberId');
        //var memberName = target.attr('data-member-id');
        //alert(memberId);
        //set value for input field with name "id"
        $('#disable-warning-dialog').find('[name="id"]').val(memberId);

        $('#disable-warning-dialog').modal('show');

        var memberData = target.attr('data-memberName');
        $('.osoba').text(memberData);

    });

    $('#rows-table').on('click', '[data-action="enable"]', function (e) {
        e.preventDefault();
        e.stopPropagation();


        //calculate target element
        var target = $(this).is('[data-action="enable"]') ? $(this) : $(this).closest('[data-action="enable"]');

        var memberId = target.attr('data-member-id');

        //verzija preko datat fje
        //var memberId =target.data('memberId');
        //var memberName = target.attr('data-member-id');
        //alert(memberId);
        //set value for input field with name "id"
        $('#enable-warning-dialog').find('[name="id"]').val(memberId);

        $('#enable-warning-dialog').modal('show');

        var memberData = target.attr('data-memberName');
        $('.osoba').text(memberData);

    });



    //SORTIRANJE
    $('[data-action="toggle-sort"]').on('click', function (e) {

        e.preventDefault();
        e.stopPropagation();

        var target = $(this).is('[data-action="toggle-sort"]') ? $(this) : $(this).closest('[data-action="toggle-sort"]');

        var sortableTbody = $('#rows-table > tbody');


        if (target.hasClass('active')) {


            target.removeClass('active');
            target.html('<i class="glyphicon glyphicon-list"></i> Change Order');



            //destroy sortable functionallity
            sortableTbody.sortable('destroy');

            //restore old html body
            sortableTbody.html(sortableTbody.data('oldHtml'));

            //hide "handle" for sorting, the icon in first column
            sortableTbody.find('[data-action="sort"]').hide();


            //hide "Save order"
            $('[data-action="save-order"]').hide();

        } else {

            target.addClass('active');

            //method html sets or gets html inside selected element
            target.html('<i class="glyphicon glyphicon-remove"></i> Cancel');

            // save tbody html before sorting under key oldHtml into its data
            sortableTbody.data('oldHtml', sortableTbody.html());

            //initialize sortable functionallity
            sortableTbody.sortable({
                handle: '[data-action="sort"]'

            });

            //sow "handle" for sorting, the icon in first column
            sortableTbody.find('[data-action="sort"]').show();
            //show "Save order"
            $('[data-action="save-order"]').show();
        }

    });


    $('[data-action="save-order"]').on('click', function (e) {

        e.preventDefault();
        e.stopPropagation();

        var memberSortedIds = $('#rows-table > tbody').sortable('toArray', {
            attribute: 'data-member-id'
        });



        //select save order form
        var saveOrderForm = $('#save-order-form');

        //find element with name "sorted_ids" in save form and set its value
        //with string wich are sorted ids separated with comma
        //ex. "12, 3, 4..."
        saveOrderForm.find('[name="sorted_ids"]').val(memberSortedIds.join(','));

        //trigerujemo submit
        saveOrderForm.trigger('submit');


    });




<?php $this->inlineScript()->captureEnd(); ?>

</script>-->