<?php

/*** treba da naslov u tabu u browseru bude Naslov Foto Galerije | Foto Galerije | Cubes CMS ***/
$this->headTitle($this->sitemapPage['title']);
$this->headTitle($this->photoGallery['title']);
$photos = $this->photos;
$photoGallery = $this->photoGallery;
$sitemapPage = $this->sitemapPage;

$this->headMeta()->appendName('description', $this->photoGallery['description']);
?>


<div id="highlighted">
    <div class="container">
        <div class="header">
            <h3 class="page-title">
                <span><?php echo $this->escape($photoGallery['title']); ?></span>
            </h3>
            <a href="<?php echo $this->sitemapPageUrl($sitemapPage['id']); ?>" class="btn btn-xs btn-default back-right"><i class="fa fa-arrow-left"></i> Back to all photo galleries</a>
        </div>
    </div>
</div>

<div class="container" style="margin-top:10px;">
	<div class="row form-group">
             <?php foreach ($photos as $photo) { ?>
        <div class="col-xs-12 col-md-4">
            
            <div class="panel panel-default">
                <div class="panel-image">
                    <img src="<?php echo $this->photoUrl($photo); ?>" class="panel-image-preview" />
                    <label for="toggle-1"></label>
                </div>
                <input type="checkbox" id="toggle-1" class="panel-image-toggle">
<!--                <div class="panel-body">
                    <h4>Title of Image</h4>
                    
                </div>-->
                <div class="panel-footer text-center">
                    <span><?php echo $this->escape($photo['title']); ?></span>
                  
                </div>
            </div>
        </div>
             <?php } ?>
<!--        <div class="col-xs-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-image hide-panel-body">
                    <img src="http://666a658c624a3c03a6b2-25cda059d975d2f318c03e90bcf17c40.r92.cf1.rackcdn.com/unsplash_52cf9489095e8_1.JPG" class="panel-image-preview" />
                    <label for="toggle-2"></label>
                </div>
                <input type="checkbox" id="toggle-2" class="panel-image-toggle">
                <div class="panel-body">
                    <h4>Title of Image</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in lobortis nisl, vitae iaculis sapien. Phasellus ultrices gravida massa luctus ornare. Suspendisse blandit quam elit, eu imperdiet neque semper et.</p>
                </div>
                <div class="panel-footer text-center">
                    <a href="#download"><span class="glyphicon glyphicon-download"></span></a>
                    <a href="#facebook"><span class="fa fa-facebook"></span></a>
                    <a href="#twitter"><span class="fa fa-twitter"></span></a>
                    <a href="#share"><span class="glyphicon glyphicon-share-alt"></span></a>
                </div>
            </div>
        </div>-->
	</div>
    
   
</div>
<?php
$this->headLink()->appendStylesheet('http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css');
$this->headLink()->appendStylesheet($this->baseUrl('/front/css/photogallery.css'));

?>