<?php

$this->headTitle($this->sitemapPage['title']);
$this->headMeta()->appendName('description', $this->sitemapPage['description']);
$photoGalleries = $this->photoGalleries;
$sitemapPage = $this->sitemapPage;
?>




<!-- SECTION3 STOP -->
<section class="section6 text-center">
    <div class="container">
        <h3 class="sectionHeadline">OUR GALLERY</h3>
        <p class="sectionP">They will have to make the best of things its an uphill climb</p>
<?php foreach ($photoGalleries as $photoGallery) {?>
        <div class="row">
 
            <div class="col-xs-12 col-sm-6 col-md-3 img-div">
                <article class="section6Articles">
                   
                    <img class="img img-responsive" src="<?php echo $this->photoGalleryLeadingPhotoUrl($photoGallery); ?>" alt="<?php echo $this->escape($photoGallery['title']) ?>"/>
<!--                    <span class="fa fa-trophy"></span>-->
                    <h4 class="h4Headline"><?php echo $this->escape($photoGallery['title']) ?></h4>
<!--                    <p class="sectionP">Rogers are blown out of their into an orbit which freezes his life </p>-->
                    <a class="readMore" href="<?php echo $this->photoGalleryUrl($photoGallery); ?>">SEE GALLERY</a>
                   
                </article>   

            </div>
 <?php }?>

 </div>
        </div>
</section>