<?php

$this->headTitle($this->sitemapPage['title']);
$this->headMeta()->appendName('description', $this->sitemapPage['description']);
?>


<main>

            <!-- SECTION 1 BLOG START -->

            <section class="section1Blog">
                <div class="container">
                    <h3 class="text-uppercase">SHOP - CHEKOUT</h3>
                    <ul class="list-unstyled list-inline ShopList">
                        <li><a href="#">Home</a><span>|</span></li>
                        <li><a href="#">Shop</a><span>|</span></li>
                        <li><a href="#">Place Order</a></li>
                    </ul>
                </div>
            </section>

            <!-- SECTION 1 BLOG STOP -->


            <!-- SECTION 2 BLOG START -->

            <section class="section2Blog">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <h3 class="sectionHeadlineBlog text-uppercase">updates from our shop</h3>
                            <p class="sectionP2">In a freak mishap ranger and its pilot captain william buck rogers are blown</p>
                        </div>

                       
                    </div>
                </div>
            </section>
            <!-- SECTION 2 BLOG STOP -->

            <!-- SECTION 3 BLOG START -->


            <section class="section3Blog">
                <div class="container">
                    <div class="row">



                        <div class="col-sx-8 col-sm-12 col-md-8 section12Element">
                           

                            <article class="blogArticle">
                                <figure class="section12Figure">
                                    <img class="img-responsive section12Img" src="img/section12-img.png" alt=""/>
                                    <div class="section12Hover">
                                        <a href="#" class="button readMore12">ADD TO CART</a>                                       
                                    </div>

                                </figure>
                                
                            </article>

                           
                        </div>

                   

                    </div>
                </div>
            </section>

            <!-- PAGINATION -->
            <section class="">
                <div class="container text-center">
                    <ul class="pagination">
                        <li><a class="paginator" href="#"><span class="fa fa-angle-left"></span></a></li>
                        <li><a class="paginator"  href="#">1</a></li>
                        <li><a class="paginator" href="#">2</a></li>
                        <li><a class="paginator" href="#">3</a></li>
                        <li><a class="paginator" href="#"><span class="fa fa-angle-right"></span></a></li>
                    </ul>
                </div>
            </section>

            <!-- SECTION 3 BLOG STOP -->




            <!-- SECTION 4 BLOG START -->

            <section class="section13">
                <div class="container text-center">
                    <div class="row">
                        <div class="col-lg-4 col-md-12">
                            <h3 class="text-uppercase text-center">subscribe our newsletter</h3>
                        </div>

                        <div class="col-lg-3 col-md-5">
                            <div class="form-group">                              
                                <input type="text" class="form-control subscribeInput" id="usr" placeholder="Your Name">
                            </div>
                        </div>

                        <div class="col-lg-3 col-md-5">
                            <div class="form-group">                              
                                <input type="text" class="form-control subscribeInput" id="usr" placeholder="Your E-Mail">
                            </div>
                        </div>

                        <div class="col-lg-2 col-md-2">
                            <div class="form-group">                              
                                <button class="btn btn-default buttonSubscribe">GO</button>
                            </div>
                        </div>

                    </div>


                </div>
            </section>


            <!-- SECTION 4 BLOG STOP -->


        </main>