

 <section class="section2 text-center">
                <div class="container">
                    <h3 class="sectionHeadline">WHAT WE DO</h3>
                    <p class="sectionP">They will have to make the best of things its an uphill climb</p>

                    <div class="row">
                        <div class="col-sm-4">
                            <article>
                                <div class="img-div">
                                    <img class="img-responsive" src="/front/img/section2-img1.jpg" alt=""/>
                                    <div class="img-hover1">
                                        <span class="spanHeadline">PET WELLNESS</span>
                                        <span class="spanSmall">We Take Care On Your Pet</span>
                                        <span class="fa fa-medkit"></span>
                                    </div>
                                </div>
                            </article>                       
                        </div> 
                        <div class="col-sm-4">
                            <article>
                                <div class="img-div">
                                    <img src="/front/img/section2-img2.jpg" alt="img2"/>
                                    <div class="img-hover2">
                                        <div class="media media1-1">
                                            <a class="media-left" href="#">
                                                <span class="fa fa-paw"></span>
                                            </a>
                                            <div class="media-body">
                                                <span class="spanHeadline2">FOODS FOR YOUR PET</span>
                                                <span class="spanSmall2">Purchase Some Quality Foods</span>

                                            </div>

                                        </div>
                                        <span class="spanSmall2-1">
                                            To a deluxe apartment in the sky. And we'll do it our way yes our way make all our dreams come true
                                            for me and you No phone no lights no motor
                                        </span>
                                        <a href="#"><span class="readMore">READ MORE</span><span class="fa fa-angle-double-right"></span></a>
                                    </div>
                                </div>
                            </article>                       
                        </div> 
                        <div class="col-sm-4">
                            <article>
                                <div class="img-div">
                                    <img class="img-responsive" src="/front/img/section2-img3.jpg" alt=""/>
                                    <div class="img-hover3">
                                        <span class="spanHeadline">PET WELLNESS</span>
                                        <span class="spanSmall">We Take Care On Your Pet</span>
                                        <span class="fa fa-medkit"></span>
                                    </div>
                                </div>
                            </article>             
                        </div>
                    </div>
            </section>
