<?php

Zend_Layout::getMvcInstance()->disableLayout();


$activeServices = $this->activeServices;
$totalNumberOfServices = $this->totalNumberOfServices;


?>


         <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="glyphicon glyphicon-cog fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><?php echo $this->escape($activeServices . ' / ' .$totalNumberOfServices );?></div>
                                    <div>active / total</div>
                                </div>
                            </div>
                        </div>
                        <a href="<?php echo $this->url(array('controller' => 'admin_services'), 'default', true);?>">
                            <div class="panel-footer">
                                <span class="pull-left">View Details- SERVICES</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>