<?php
$sitemapPage = $this->sitemapPage;
$products = $this->products;
$pets = $this->pets;
$categories = $this->categories;
$producers = $this->producers;


$this->headTitle($sitemapPage['title']);
$this->headMeta()->appendName('description', $sitemapPage['description']);


$cmsSitemapPageDbTable = new Application_Model_DbTable_CmsSitemapPages();
?>
<!-- SECTION 1 SHOP START -->

            <section class="section1Blog">
                <div class="container">
                    <h3 class="text-uppercase">SHOP - CHEKOUT</h3>
                    <ul class="list-unstyled list-inline ShopList">
                        <li><a href="#">Home</a><span>|</span></li>
                        <li><a href="#">Shop</a><span>|</span></li>
                        <li><a href="#">Pet List</a></li>
                    </ul>
                </div>
            </section>

            <!-- SECTION 1 SHOP STOP -->

            <!-- SECTION 2 SHOP START -->
            <section>
                <div class="showFiltersClick">
                    <p class="shopFilters">SHOW / HIDE FILTERS<a class="fa fa-cogs pull-right showHideFilters" href="javascript:void(0)"></a></p>
                </div>

                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-md-3 col-lg-3 filterMenu">
                            <article>
                                <form>
                                    <h4 class="text-uppercase shopH4-1">select pet</h4>
                                    <ul class="list-unstyled">
                                        <?php foreach ($pets as $pet) {?>
                                        <li>
                                            <div class="checkbox">
                                                <label><input type="checkbox" value=""><?php echo $this->escape($pet['title']);?></label><span class="pull-right"><a class="checkboxText" href="">158</a></span>
                                            </div>
                                        </li>

                                        <?php }?>
                                    </ul>
                                </form>
                            </article>

                            <article>

                                <h4 class="text-uppercase shopH4-2">Filter by price</h4>

                                <!-- RANGE SLIDER -->
                                <div class="rangeSliderForm">
                                    <form>
                                        <div class="nstSlider" data-range_min="5" data-range_max="3000" data-cur_min="500" data-cur_max="2500">

                                            <div class="bar"></div>
                                            <div class="leftGrip"></div>
                                            <div class="rightGrip"></div>
                                        </div>
                                        <span class="priceRange">Price: $ </span><span class="leftLabel"></span><span  class="priceRange"> - </span>
                                        <span class="priceRange">$ </span><span class="rightLabel"></span>
                                        <button class="btn-default pull-right filterButton">FILTER</button>
                                    </form>
                                </div>
                            </article>

                            <article>
                                <form>
                                    <h4 class="text-uppercase shopH4-3">select category</h4>
                                    <ul class="list-unstyled">
                                         <?php foreach ($categories as $category) {?>
                                        <li>
                                            <div class="checkbox">
                                                <label><input type="checkbox" value=""><?php echo $this->escape($category['title']);?></label><span class="pull-right"><a class="checkboxText" href="">72</a></span>
                                            </div>
                                        </li>
                                            <?php }?>
                                    </ul>
                                </form>


                                <h4 class="text-uppercase mediaH4">recent post</h4>

                                <!-- SIDE MEDIA 1 -->
                                <div class="media blogMedia">
                                    <div class="media-left">
                                        <a href="#">
                                            <img class="media-object" src="/front/img/blogSide-img.png" alt=""/>
                                        </a>
                                    </div>
                                    <div class="media-body">
                                        <p class="media-heading">PITT BULL</p>
                                        <span class="blogSideSpan">$ 120.00</span>
                                        <ul class="list-inline">
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStarGray"></span></a></li>
                                        </ul>
                                    </div>
                                </div>

                                <!-- SIDE MEDIA 2 -->
                                <div class="media blogMedia">
                                    <div class="media-left">
                                        <a href="#">
                                            <img class="media-object" src="/front/img/blogSide-img.png" alt=""/>
                                        </a>
                                    </div>
                                    <div class="media-body">
                                        <p class="media-heading">BROWN CAT</p>
                                        <span class="blogSideSpan">$ 76.00</span>
                                        <ul class="list-inline">
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                        </ul>
                                    </div>
                                </div>

                                <!-- SIDE MEDIA 3 -->

                                <div class="media blogMedia">
                                    <div class="media-left">
                                        <a href="#">
                                            <img class="media-object" src="/front/img/blogSide-img.png" alt=""/>
                                        </a>
                                    </div>
                                    <div class="media-body">
                                        <p class="media-heading">WILD RABBIT</p>
                                        <span class="blogSideSpan">$ 80.00</span>
                                        <ul class="list-inline">
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStarGray"></span></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </article>
                        </div>

                        <div class="col-xs-12 col-md-9">

                            <h3 class="sectionHeadline text-center shopHeadline">Our Best Quality Products</h3>
                            <p class="sectionP text-center">In a freak mishap ranger and its pilot captain william buck rogers are blown</p>



                            <div class="row">
                                <div id="Container">
                                    <nav class="clearfix filterNav text-center">
                                        <ol class="list-unstyled text-center">
                                            <li class="filter" data-filter="all">All</li>
                                            <?php foreach ($pets as $pet) {?>
                                            <li class="filter" data-filter=".<?php echo $this->escape($pet['url_slug']);?>"><?php echo $this->escape($pet['title']);?></li>
<!--                                            <li class="filter" data-filter=".companion">Companion</li>
                                            <li class="filter" data-filter=".hairless">Hairless</li>
                                            <li class="filter" data-filter=".fluffy-hair">Fluffy Hair</li>-->
                                            <?php }?>
                                        </ol>
                                    </nav>
                                    <div class="my-img">
                                        <?php foreach ($products as $product) {?>
                                        <div class="col-md-6 col-lg-4 mix <?php echo $cmsSitemapPageDbTable->getSitemapPageById($product['pet_id'])['url_slug']; ?>" data-myorder="1">
                                            <article>
                                                <figure class="figureProducts">
                                                    <img class="img-responsive productImg" src="/front/img/shopImg.png" alt=""/>                                    
                                                    <div class="contentAbsolute">
                                                        <button class="button toCart">ADD TO CART</button>
                                                        <div class="faAbsolute">
                                                            <a href="javascript:void(0)"><span class="fa fa-heart-o"></span></a>
                                                            <a href="#"><span class="fa fa-arrows-alt"></span></a>
                                                        </div>
                                                    </div>
                                                </figure>
                                                <div class="underContent">
                                                    <div class="row">
                                                        <div class="col-xs-8">
                                                            <article class="productName">
                                                                <h5>HUNTER</h5>
                                                                <ul class="list-inline list-unstyled">
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star-half-o" href="#"></a></li>
                                                                </ul>
                                                            </article>
                                                        </div>
                                                        <div class="col-xs-4">
                                                            <article class="productPrice">
                                                                <span class="price">$120.00</span>
                                                            </article>
                                                        </div>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>
                                        
                                        <?php }?>
                                        
                                        
                                        
                                        
                                        <div class="col-md-6 col-lg-4 mix companion" data-myorder="2">
                                            <article>
                                                <figure class="figureProducts">
                                                    <img class="img-responsive productImg" src="/front/img/shopImg.png" alt=""/>                                    
                                                    <div class="contentAbsolute">
                                                        <button class="button toCart">ADD TO CART</button>
                                                        <div class="faAbsolute">
                                                            <a href="javascript:void(0)"><span class="fa fa-heart-o"></span></a>
                                                            <a href="#"><span class="fa fa-arrows-alt"></span></a>
                                                        </div>
                                                    </div>
                                                </figure>
                                                <div class="underContent">
                                                    <div class="row">
                                                        <div class="col-xs-8">
                                                            <article class="productName">
                                                                <h5>BROWN CAT</h5>
                                                                <ul class="list-inline list-unstyled">
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star-half-o" href="#"></a></li>
                                                                </ul>
                                                            </article>
                                                        </div>
                                                        <div class="col-xs-4">
                                                            <article class="productPrice">
                                                                <span class="price">$150.00</span>
                                                            </article>
                                                        </div>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>
                                        <div class="col-md-6 col-lg-4 mix hairless" data-myorder="3">
                                            <article>
                                                <figure class="figureProducts">
                                                    <img class="img-responsive productImg" src="/front/img/shopImg.png" alt=""/>                                    
                                                    <div class="contentAbsolute">
                                                        <button class="button toCart">ADD TO CART</button>
                                                        <div class="faAbsolute">
                                                            <a href="javascript:void(0)"><span class="fa fa-heart-o"></span></a>
                                                            <a href="#"><span class="fa fa-arrows-alt"></span></a>
                                                        </div>
                                                    </div>
                                                </figure>
                                                <div class="underContent">
                                                    <div class="row">
                                                        <div class="col-xs-8">
                                                            <article class="productName">
                                                                <h5>TRAINED PUG</h5>
                                                                <ul class="list-inline list-unstyled">
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                </ul>
                                                            </article>
                                                        </div>
                                                        <div class="col-xs-4">
                                                            <article class="productPrice">
                                                                <span class="price">$280.00</span>
                                                            </article>
                                                        </div>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>

                                        <div class="col-md-6 col-lg-4 mix fluffy-hair" data-myorder="4">
                                            <article>
                                                <figure class="figureProducts">
                                                    <img class="img-responsive productImg" src="/front/img/shopImg.png" alt=""/>                                    
                                                    <div class="contentAbsolute">
                                                        <button class="button toCart">ADD TO CART</button>
                                                        <div class="faAbsolute">
                                                            <a href="javascript:void(0)"><span class="fa fa-heart-o"></span></a>
                                                            <a href="#"><span class="fa fa-arrows-alt"></span></a>
                                                        </div>
                                                    </div>
                                                </figure>
                                                <div class="underContent">
                                                    <div class="row">
                                                        <div class="col-xs-8">
                                                            <article class="productName">
                                                                <h5>BABY RABBIT</h5>
                                                                <ul class="list-inline list-unstyled">
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star-half-o" href="#"></a></li>
                                                                </ul>
                                                            </article>
                                                        </div>
                                                        <div class="col-xs-4">
                                                            <article class="productPrice">
                                                                <span class="price">$96.00</span>
                                                            </article>
                                                        </div>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>

                                        <div class="col-md-6 col-lg-4 mix hunting" data-myorder="5">
                                            <article>
                                                <figure class="figureProducts">
                                                    <img class="img-responsive productImg" src="/front/img/shopImg.png" alt=""/>                                    
                                                    <div class="contentAbsolute">
                                                        <button class="button toCart">ADD TO CART</button>
                                                        <div class="faAbsolute">
                                                            <a href="javascript:void(0)"><span class="fa fa-heart-o"></span></a>
                                                            <a href="#"><span class="fa fa-arrows-alt"></span></a>
                                                        </div>
                                                    </div>
                                                </figure>
                                                <div class="underContent">
                                                    <div class="row">
                                                        <div class="col-xs-8">
                                                            <article class="productName">
                                                                <h5>MALTESE</h5>
                                                                <ul class="list-inline list-unstyled">
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star-half-o" href="#"></a></li>
                                                                </ul>
                                                            </article>
                                                        </div>
                                                        <div class="col-xs-4">
                                                            <article class="productPrice">
                                                                <span class="price">$72.00</span>
                                                            </article>
                                                        </div>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>

                                        <div class="col-md-6 col-lg-4 mix companion" data-myorder="6">
                                            <article>
                                                <figure class="figureProducts">
                                                    <img class="img-responsive productImg" src="front/img/shopImg.png" alt=""/>                                    
                                                    <div class="contentAbsolute">
                                                        <button class="button toCart">ADD TO CART</button>
                                                        <div class="faAbsolute">
                                                            <a href="javascript:void(0)"><span class="fa fa-heart-o"></span></a>
                                                            <a href="#"><span class="fa fa-arrows-alt"></span></a>
                                                        </div>
                                                    </div>
                                                </figure>
                                                <div class="underContent">
                                                    <div class="row">
                                                        <div class="col-xs-8">
                                                            <article class="productName">
                                                                <h5>WILD RABBIT</h5>
                                                                <ul class="list-inline list-unstyled">
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                </ul>
                                                            </article>
                                                        </div>
                                                        <div class="col-xs-4">
                                                            <article class="productPrice">
                                                                <span class="price">$80.00</span>
                                                            </article>
                                                        </div>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>

                                        <div class="col-md-6 col-lg-4 mix hairless" data-myorder="7">
                                            <article>
                                                <figure class="figureProducts">
                                                    <img class="img-responsive productImg" src="front/img/shopImg.png" alt=""/>                                    
                                                    <div class="contentAbsolute">
                                                        <button class="button toCart">ADD TO CART</button>
                                                        <div class="faAbsolute">
                                                            <a href="javascript:void(0)"><span class="fa fa-heart-o"></span></a>
                                                            <a href="#"><span class="fa fa-arrows-alt"></span></a>
                                                        </div>
                                                    </div>
                                                </figure>
                                                <div class="underContent">
                                                    <div class="row">
                                                        <div class="col-xs-8">
                                                            <article class="productName">
                                                                <h5>COONHOUND</h5>
                                                                <ul class="list-inline list-unstyled">
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star-half-o" href="#"></a></li>
                                                                </ul>
                                                            </article>
                                                        </div>
                                                        <div class="col-xs-4">
                                                            <article class="productPrice">
                                                                <span class="price">$60.00</span>
                                                            </article>
                                                        </div>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>

                                        <div class="col-md-6 col-lg-4 mix fluffy-hair" data-myorder="8">
                                            <article>
                                                <figure class="figureProducts">
                                                    <img class="img-responsive productImg" src="front/img/shopImg.png" alt=""/>                                    
                                                    <div class="contentAbsolute">
                                                        <button class="button toCart">ADD TO CART</button>
                                                        <div class="faAbsolute">
                                                            <a href="javascript:void(0)"><span class="fa fa-heart-o"></span></a>
                                                            <a href="#"><span class="fa fa-arrows-alt"></span></a>
                                                        </div>
                                                    </div>
                                                </figure>
                                                <div class="underContent">
                                                    <div class="row">
                                                        <div class="col-xs-8">
                                                            <article class="productName">
                                                                <h5>BABY CAT</h5>
                                                                <ul class="list-inline list-unstyled">
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star-half-o" href="#"></a></li>
                                                                </ul>
                                                            </article>
                                                        </div>
                                                        <div class="col-xs-4">
                                                            <article class="productPrice">
                                                                <span class="price">$224.00</span>
                                                            </article>
                                                        </div>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>

                                        <div class="col-md-6 col-lg-4 mix hunting" data-myorder="9">
                                            <article>
                                                <figure class="figureProducts">
                                                    <img class="img-responsive productImg" src="front/img/shopImg.png" alt=""/>                                    
                                                    <div class="contentAbsolute">
                                                        <button class="button toCart">ADD TO CART</button>
                                                        <div class="faAbsolute">
                                                            <a href="javascript:void(0)"><span class="fa fa-heart-o"></span></a>
                                                            <a href="#"><span class="fa fa-arrows-alt"></span></a>
                                                        </div>
                                                    </div>
                                                </figure>
                                                <div class="underContent">
                                                    <div class="row">
                                                        <div class="col-xs-8">
                                                            <article class="productName">
                                                                <h5>LABRADOR</h5>
                                                                <ul class="list-inline list-unstyled">
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                </ul>
                                                            </article>
                                                        </div>
                                                        <div class="col-xs-4">
                                                            <article class="productPrice">
                                                                <span class="price">$540.00</span>
                                                            </article>
                                                        </div>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>

                                        <div class="col-md-6 col-lg-4 mix companion" data-myorder="10">
                                            <article>
                                                <figure class="figureProducts">
                                                    <img class="img-responsive productImg" src="front/img/shopImg.png" alt=""/>                                    
                                                    <div class="contentAbsolute">
                                                        <button class="button toCart">ADD TO CART</button>
                                                        <div class="faAbsolute">
                                                            <a href="javascript:void(0)"><span class="fa fa-heart-o"></span></a>
                                                            <a href="#"><span class="fa fa-arrows-alt"></span></a>
                                                        </div>
                                                    </div>
                                                </figure>
                                                <div class="underContent">
                                                    <div class="row">
                                                        <div class="col-xs-8">
                                                            <article class="productName">
                                                                <h5>DOUBLE COLOR PARROT</h5>
                                                                <ul class="list-inline list-unstyled">
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star-half-o" href="#"></a></li>
                                                                </ul>
                                                            </article>
                                                        </div>
                                                        <div class="col-xs-4">
                                                            <article class="productPrice">
                                                                <span class="price">$140.00</span>
                                                            </article>
                                                        </div>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>

                                        <div class="col-md-6 col-lg-4 mix hairless" data-myorder="11">
                                            <article>
                                                <figure class="figureProducts">
                                                    <img class="img-responsive productImg" src="front/img/shopImg.png" alt=""/>                                    
                                                    <div class="contentAbsolute">
                                                        <button class="button toCart">ADD TO CART</button>
                                                        <div class="faAbsolute">
                                                            <a href="javascript:void(0)"><span class="fa fa-heart-o"></span></a>
                                                            <a href="#"><span class="fa fa-arrows-alt"></span></a>
                                                        </div>
                                                    </div>
                                                </figure>
                                                <div class="underContent">
                                                    <div class="row">
                                                        <div class="col-xs-8">
                                                            <article class="productName">
                                                                <h5>SLED DOG</h5>
                                                                <ul class="list-inline list-unstyled">
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star-half-o" href="#"></a></li>
                                                                </ul>
                                                            </article>
                                                        </div>
                                                        <div class="col-xs-4">
                                                            <article class="productPrice">
                                                                <span class="price">$150.00</span>
                                                            </article>
                                                        </div>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>

                                        <div class="col-md-6 col-lg-4 mix fluffy-hair" data-myorder="12">
                                            <article>
                                                <figure class="figureProducts">
                                                    <img class="img-responsive productImg" src="front/img/shopImg.png" alt=""/>                                    
                                                    <div class="contentAbsolute">
                                                        <button class="button toCart">ADD TO CART</button>
                                                        <div class="faAbsolute">
                                                            <a href="javascript:void(0)"><span class="fa fa-heart-o"></span></a>
                                                            <a href="#"><span class="fa fa-arrows-alt"></span></a>
                                                        </div>
                                                    </div>
                                                </figure>
                                                <div class="underContent">
                                                    <div class="row">
                                                        <div class="col-xs-8">
                                                            <article class="productName">
                                                                <h5>TALKING PARROT</h5>
                                                                <ul class="list-inline list-unstyled">
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                    <li><a class="fa fa-star" href="#"></a></li>
                                                                </ul>
                                                            </article>
                                                        </div>
                                                        <div class="col-xs-4">
                                                            <article class="productPrice">
                                                                <span class="price">$970.00</span>
                                                            </article>
                                                        </div>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </section>
            

            <!-- PAGINATION -->
            <section class="">
                <div class="container text-center">
                    <ul class="pagination">
                        <li><a class="paginator" href="#"><span class="fa fa-angle-left"></span></a></li>
                        <li><a class="paginator"  href="#">1</a></li>
                        <li><a class="paginator" href="#">2</a></li>
                        <li><a class="paginator" href="#">3</a></li>
                        <li><a class="paginator" href="#"><span class="fa fa-angle-right"></span></a></li>
                    </ul>
                </div>
            </section>

            <!-- SECTION 3 BLOG STOP -->
            
   


 <?php
//dodatni css na nasu stranicu
//$this->headLink()->appendStylesheet($this->baseUrl('/front/css/jquery.nstSlider.css'));
$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css');
$this->headLink()->appendStylesheet($this->baseUrl('/front/resources/demos/style.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/front/css/vendor/jquery.nstSlider.css'));
$this->inlineScript()->appendFile($this->baseUrl('/front/js/vendor/jquery.nstSlider.js'));
$this->inlineScript()->appendFile($this->baseUrl('/front/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js'));
$this->inlineScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.js');

$this->inlineScript()->appendFile($this->baseUrl('/front/js/vendor/jquery.mixitup.min.js'));
?>
            <script>
                <?php $this->inlineScript()->captureStart(); ?>
              window.jQuery || document.write(<?php $this->baseUrl('<script src="front/js/vendor/jquery-1.11.2.js"><\/script>');?>)
            $(function () {
                $('#Container').mixItUp({
                    animation: {
                        enable: true,
                        effects: 'fade scale',
                        duration: 1500
                    }
                });
            });
        </script>
        <!-- SHOW / HIDE FILTER MENU -->
        <script>
            $(window).resize(function () {
                if ($(window).width() < 768) {
                    $('.filterMenu').hide();
                } else {
                    $('.filterMenu').show();
                }
            });

            $("a.showHideFilters").click(function () {
                $("div.filterMenu").toggle('fade');
            });
            <?php $this->inlineScript()->captureEnd(); ?>
        </script>

