<?php

$products = $this->products;
$pets = $this->pets;
$category = $this->category;
$producer = $this->producer;
$product = $this->product;
$similiarProducts = $this->similiarProducts;
$shopSitemapPages = $this->shopSitemapPages;


$this->headTitle('Product - ' . $product['title']);
?>

 <section class="section1Blog">
                <div class="container">
                    <h3 class="text-uppercase">SHOP - CHEKOUT</h3>
                    <ul class="list-unstyled list-inline ShopList">
                        <li><a href="<?php echo $this->url(array('controller' => 'index','action'=> 'index'), 'default', true)?>">Home</a><span>|</span></li>
                        <li><a href="<?php echo $this->sitemapPageUrl($shopSitemapPages['id']);?>">Shop</a><span>|</span></li>
                        <li><a href="<?php echo $this->productUrl($product);?>"><?php echo $this->escape($product['title']);?></a></li>
                    </ul>
                </div>
            </section>

            <!-- SECTION 1 SHOP STOP -->

            <!-- SECTION 2 SHOP START -->
            <section>
                <div class="showFiltersClick">
                    <p class="shopFilters">SHOW / HIDE FILTERS<a class="fa fa-cogs pull-right showHideFilters" href="javascript:void(0)"></a></p>
                </div>

                <div class="container">
                    <div class="row">
<!--                        <div class="col-xs-12 col-md-3 col-lg-3 filterMenu">
                            <article>
                                <form>
                                    <h4 class="text-uppercase shopH4-1">select pet</h4>
                                    <ul class="list-unstyled">
                                        <li>
                                            <div class="checkbox">
                                                <label><input type="checkbox" value="">Maltese</label><span class="pull-right"><a class="checkboxText" href="">158</a></span>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="checkbox">
                                                <label><input type="checkbox" value="">Pitt Bull</label><span class="pull-right"><a class="checkboxText" href="">430</a></span>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="checkbox">
                                                <label><input type="checkbox" value="">Sled Dogs</label><span class="pull-right"><a class="checkboxText" href="">279</a></span>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="checkbox">
                                                <label><input type="checkbox" value="">Purebred</label><span class="pull-right"><a class="checkboxText" href="">365</a></span>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="checkbox">
                                                <label><input type="checkbox" value="">Coonhound</label><span class="pull-right"><a class="checkboxText" href="">189</a></span>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="checkbox">
                                                <label><input type="checkbox" value="">Molosser</label><span class="pull-right"><a class="checkboxText" href="">763</a></span>
                                            </div>
                                        </li>
                                    </ul>
                                </form>
                            </article>

                            <article>

                                <h4 class="text-uppercase shopH4-2">Filter by price</h4>

                                 RANGE SLIDER 
                                <div class="rangeSliderForm">
                                    <form>
                                        <div class="nstSlider" data-range_min="5" data-range_max="3000" data-cur_min="500" data-cur_max="2500">

                                            <div class="bar"></div>
                                            <div class="leftGrip"></div>
                                            <div class="rightGrip"></div>
                                        </div>
                                        <span class="priceRange">Price: $ </span><span class="leftLabel"></span><span  class="priceRange"> - </span>
                                        <span class="priceRange">$ </span><span class="rightLabel"></span>
                                        <button class="btn-default pull-right filterButton">FILTER</button>
                                    </form>
                                </div>
                            </article>

                            <article>
                                <form>
                                    <h4 class="text-uppercase shopH4-3">select pet</h4>
                                    <ul class="list-unstyled">
                                        <li>
                                            <div class="checkbox">
                                                <label><input type="checkbox" value="">Hunting</label><span class="pull-right"><a class="checkboxText" href="">72</a></span>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="checkbox">
                                                <label><input type="checkbox" value="">Companion</label><span class="pull-right"><a class="checkboxText" href="">24</a></span>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="checkbox">
                                                <label><input type="checkbox" value="">Hairless</label><span class="pull-right"><a class="checkboxText" href="">10</a></span>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="checkbox">
                                                <label><input type="checkbox" value="">Fighting Breeds</label><span class="pull-right"><a class="checkboxText" href="">56</a></span>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="checkbox">
                                                <label><input type="checkbox" value="">Molossers</label><span class="pull-right"><a class="checkboxText" href="">12</a></span>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="checkbox">
                                                <label><input type="checkbox" value="">Fluffy Hair</label><span class="pull-right"><a class="checkboxText" href="">88</a></span>
                                            </div>
                                        </li>
                                    </ul>


                                </form>


                                <h4 class="text-uppercase mediaH4">recent post</h4>

                                 SIDE MEDIA 1 
                                <div class="media blogMedia">
                                    <div class="media-left">
                                        <a href="#">
                                            <img class="media-object" src="img/blogSide-img.png" alt=""/>
                                        </a>
                                    </div>
                                    <div class="media-body">
                                        <p class="media-heading">PITT BULL</p>
                                        <span class="blogSideSpan">$ 120.00</span>
                                        <ul class="list-inline">
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStarGray"></span></a></li>
                                        </ul>
                                    </div>
                                </div>

                                 SIDE MEDIA 2 
                                <div class="media blogMedia">
                                    <div class="media-left">
                                        <a href="#">
                                            <img class="media-object" src="img/blogSide-img.png" alt=""/>
                                        </a>
                                    </div>
                                    <div class="media-body">
                                        <p class="media-heading">BROWN CAT</p>
                                        <span class="blogSideSpan">$ 76.00</span>
                                        <ul class="list-inline">
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                        </ul>
                                    </div>
                                </div>

                                 SIDE MEDIA 3 

                                <div class="media blogMedia">
                                    <div class="media-left">
                                        <a href="#">
                                            <img class="media-object" src="img/blogSide-img.png" alt=""/>
                                        </a>
                                    </div>
                                    <div class="media-body">
                                        <p class="media-heading">WILD RABBIT</p>
                                        <span class="blogSideSpan">$ 80.00</span>
                                        <ul class="list-inline">
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStar"></span></a></li>
                                            <li><a href="#"><span class="fa fa-star sideStarGray"></span></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </article>
                        </div>-->

                        <div class="col-xs-12 col-md-9 shopDetailsContent">

                            <div class="row sideContent">
<!--                                <div class="col-lg-6 articleDetails">
                                    <img class="img-responsive detailsImage" src="img/shopDetails-Img.png" alt=""/>
                                </div>-->

                                <div class="col-lg-6 articleDetails">
                                    <img alt="<?php echo $this->escape($product['title']); ?>" title="<?php echo $this->escape($product['title']); ?>" src="<?php echo $this->productImgUrl($product); ?>" class="img-responsive detailsImage">
                                </div>
                                <div class="col-lg-6">
                                    <div class="fullreviews">
                                        <h4 class="text-uppercase h4sideDetails"><?php echo $this->escape($product['title']);?></h4>
                                        <span class="priceSpanDetails"><?php echo $this->escape($product['price']);?></span>
<!--                                        <span class="priceOldSpanDetails">$85</span>
                                        <div class="reviewDetails">
                                            <a class="reviews" href="#"><span class="priceOldSpanDetails1">5 Review(s)</span></a>
                                            <span class="spanSplitter"> | </span>
                                            <a class="reviews" href="#"><span class="priceOldSpanDetails1">Add Your Review</span></a>

                                            <ul class="list-inline list-unstyled detailsRating">
                                                <li><a class="fa fa-star" href="#"></a></li>
                                                <li><a class="fa fa-star" href="#"></a></li>
                                                <li><a class="fa fa-star" href="#"></a></li>
                                                <li><a class="fa fa-star" href="#"></a></li>
                                                <li><a class="fa fa-star-half-o" href="#"></a></li>
                                            </ul>

                                        </div>-->
                                        <div class="aboutDetails">
                                            <p class="detailsParagraphs">
                                                <?php echo $this->escape($product['about']);?>  
                                            </p>
                                        </div>
                                        <form>
                                            <div class="row colorsSizes">
<!--
                                                <div class="colorPicker col-xs-12 col-sm-6">
                                                    <h4 class="h4sideDetails">Color:</h4>
                                                    <ul class="list-inline list-unstyled colors">
                                                        <li class="colorPickerBorder"><a class="color1" href="#"></a></li>
                                                        <li class="colorPickerBorder"><a class="color2" href="#"></a></li>
                                                        <li class="colorPickerBorder"><a class="color3" href="#"></a></li>
                                                        <li class="colorPickerBorder"><a class="color4" href="#"></a></li>
                                                        <li class="colorPickerBorder"><a class="color5" href="#"></a></li>
                                                        <li class="colorPickerBorder"><a class="color6" href="#"></a></li>
                                                    </ul>
                                                </div>-->
<!--                                                <div class="col-sm-6 likeCol">
                                                    <ul class="list-inline list-unstyled connectList">
                                                        <li class="likeDetails"><a class="fa fa-heart-o" href="javascript:void(0)"></a></li>
                                                        <li class="shareDetails"><a class="fa fa-share" href="javascript:void(0)"></a></li>
                                                        <li class="emailDetails"><a class="fa fa-envelope-o" href="mailto:example@mail.com"></a></li>
                                                    </ul>
                                                </div>-->



                                            </div>
                                            <div class="row">
<!--
                                                <div class="col-xs-6 col-md-3 text-right">
                                                    <div class="form-group">
                                                        <span class="qtySpan">Qty: </span>
                                                        <select class=" selectDetails" id="sel1">
                                                            <option>1</option>
                                                            <option>2</option>
                                                            <option>3</option>
                                                            <option>4</option>
                                                            <option>5</option>
                                                        </select>
                                                    </div>
                                                </div>-->
<!--
                                                <div class="col-xs-6 col-md-3 text-left">
                                                    <span class="sizeSpan">Size: </span>
                                                    <select class=" selectDetails" id="sel1">
                                                        <option>XS</option>
                                                        <option>SM</option>
                                                        <option>M</option>
                                                        <option>L</option>
                                                        <option>XL</option>
                                                    </select>
                                                </div>-->
                                                <div class="col-xs-12 col-md-6">
                                                    <button class="btn-default detailsButton">ADD TO CART</button>
                                                </div>

                                                <div class="col-xs-12 divAvailable">
                                                    <span class="availableSpan text-left">Producer: </span>
                                                    <span class="stockSpan text-left"><?php echo $this->escape($producer['name']);?> </span>
                                                    </div>
                                                    <div class="col-xs-12 divAvailable">
                                                    <span class="availableSpan text-left">Category: </span>
                                                    <span class="stockSpan text-left"><?php echo $this->escape($category['title']);?></span>
                                                </div>

                                            </div>
                                        </form>
                                    </div>
                                </div>



                                <div class="col-xs-12">
                                    <ul class="nav nav-tabs">
                                        <li class="active"><a data-toggle="tab" href="#home">PRODUCT DETAILS</a></li>
                                        <li><a data-toggle="tab" href="#menu1">REVIEWS</a></li>
                                        <li><a data-toggle="tab" href="#menu2">PRODUCT TAGS</a></li>
                                    </ul>

                                    <div class="tab-content">
                                        <div id="home" class="tab-pane fade in active">
                                            <p class="tabsParagraphs">
                                                <?php echo $this->escape($product['about']); ?>
                                            </p>
                                        </div>
                                        <div id="menu1" class="tab-pane fade">
                                            <p class="tabsParagraphs">
                                                It is a long established fact that a reader will be distracted by the readable
                                                content of a page when looking at its layout. The point of using Lorem Ipsum is
                                                that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, 
                                                content here', making it look like readable English.
                                            </p>
                                        </div>
                                        <div id="menu2" class="tab-pane fade">
                                            <p class="tabsParagraphs">
                                                Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text,
                                                and a search for 'lorem ipsum' will uncover many web sites still in their infancy. 
                                                Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <h3 class="sectionHeadlineShop text-left shopHeadline">SIMILAR PRODUCTS</h3>
                            <p class="sectionP text-left">In a freak mishap ranger and its pilot captain william buck rogers are blown</p>
                            <div class="row">
                                <?php foreach($similiarProducts as $similiarProduct) { ?>
                                <div class="col-md-6 col-lg-4 mix companion" data-myorder="10">
                                    <article>
                                        <figure class="figureProducts">
                                            <img class="img-responsive productImg" src="<?php echo $this->productImgUrl($similiarProduct);?>" title="<?php echo $this->escape($similiarProduct['title']);?>" alt="<?php echo $this->escape($similiarProduct['title']);?>"/> 
                                            <?php if($similiarProduct['action']) {?>
                                            <p class="productP">SALE</p>
                                            <?php }?>
                                            <div class="contentAbsolute">
                                                
                                                <div class="faAbsolute">
                                                    <a href="javascript:void(0)"><span class="fa fa-heart-o"></span></a>
                                                    <a href="#"><span class="fa fa-arrows-alt"></span></a>
                                                    
                                                </div>
                                            </div>
                                        </figure>
                                        <div class="underContent">
                                            <div class="row">
                                                <div class="col-xs-8">
                                                    <article class="productName">
                                                        <h5><?php echo $this->escape($similiarProduct['title']);?></h5>
                                                        <ul class="list-inline list-unstyled">
                                                            <li><a class="fa fa-star" href="#"></a></li>
                                                            <li><a class="fa fa-star" href="#"></a></li>
                                                            <li><a class="fa fa-star" href="#"></a></li>
                                                            <li><a class="fa fa-star" href="#"></a></li>
                                                            <li><a class="fa fa-star-half-o" href="#"></a></li>
                                                        </ul>
                                                        
                                                    </article>
                                                    
                                                </div>
                                                
                                                <div class="col-xs-4">
                                                    <article class="productPrice">
                                                        <span class="price"><?php echo $this->escape($similiarProduct['price']);?></span>
                                                    </article>
                                                </div>
                                                <a href="<?php $this->productImgUrl($similiarProduct); ?>" class="button toCart">SEE DETAILS</a>
                                            </div>
                                        </div>
                                    </article>
                                </div>
                                <?php }?>

<!--                                <div class="col-md-6 col-lg-4 mix hairless" data-myorder="11">
                                    <article>
                                        <figure class="figureProducts">
                                            <img class="img-responsive productImg" src="img/shopImg.png" alt=""/>                                    
                                            <div class="contentAbsolute">
                                                <button class="button toCart">ADD TO CART</button>
                                                <div class="faAbsolute">
                                                    <a href="javascript:void(0)"><span class="fa fa-heart-o"></span></a>
                                                    <a href="#"><span class="fa fa-arrows-alt"></span></a>
                                                </div>
                                            </div>
                                        </figure>
                                        <div class="underContent">
                                            <div class="row">
                                                <div class="col-xs-8">
                                                    <article class="productName">
                                                        <h5>PET TOYS</h5>
                                                        <ul class="list-inline list-unstyled">
                                                            <li><a class="fa fa-star" href="#"></a></li>
                                                            <li><a class="fa fa-star" href="#"></a></li>
                                                            <li><a class="fa fa-star" href="#"></a></li>
                                                            <li><a class="fa fa-star" href="#"></a></li>
                                                            <li><a class="fa fa-star-half-o" href="#"></a></li>
                                                        </ul>
                                                    </article>
                                                </div>
                                                <div class="col-xs-4">
                                                    <article class="productPrice">
                                                        <span class="price">$150.00</span>
                                                    </article>
                                                </div>
                                            </div>
                                        </div>
                                    </article>
                                </div>

                                <div class="col-md-6 col-lg-4 mix fluffy-hair" data-myorder="12">
                                    <article>
                                        <figure class="figureProducts">
                                            <img class="img-responsive productImg" src="" alt=""/>                               
                                            <p class="productP">NEW</p>
                                            <div class="contentAbsolute">
                                                <button class="button toCart">ADD TO CART</button>
                                                <div class="faAbsolute">
                                                    <a href="javascript:void(0)"><span class="fa fa-heart-o"></span></a>
                                                    <a href="#"><span class="fa fa-arrows-alt"></span></a>
                                                </div>
                                            </div>
                                        </figure>
                                        <div class="underContent">
                                            <div class="row">
                                                <div class="col-xs-8">
                                                    <article class="productName">
                                                        <h5>PET OUTFITS</h5>
                                                        <ul class="list-inline list-unstyled">
                                                            <li><a class="fa fa-star" href="#"></a></li>
                                                            <li><a class="fa fa-star" href="#"></a></li>
                                                            <li><a class="fa fa-star" href="#"></a></li>
                                                            <li><a class="fa fa-star" href="#"></a></li>
                                                            <li><a class="fa fa-star-half-o" href="#"></a></li>
                                                        </ul>
                                                    </article>
                                                </div>
                                                <div class="col-xs-4">
                                                    <article class="productPrice">
                                                        <span class="price">$280.00</span>
                                                    </article>
                                                </div>
                                            </div>
                                        </div>
                                    </article>
                                </div>-->
                            </div>
                        </div>
                    </div>
                </div>
            </section>



            <!-- SECTION 2 SHOP STOP -->






            <!-- PAGINATION -->
            <section class="">
                <div class="container text-center">
                    <ul class="pagination">
                        <li><a class="paginator" href="#"><span class="fa fa-angle-left"></span></a></li>
                        <li><a class="paginator"  href="#">1</a></li>
                        <li><a class="paginator" href="#">2</a></li>
                        <li><a class="paginator" href="#">3</a></li>
                        <li><a class="paginator" href="#"><span class="fa fa-angle-right"></span></a></li>
                    </ul>
                </div>
            </section>

            <!-- SECTION 3 BLOG STOP -->



<?php
$this->inlineScript()->appendFile($this->baseUrl('/front/js/vendor/jquery-1.11.2.js'));

?>