 <!-- SECTION 8 START -->
            <section class="section8">
                <div class="container text-center">

                    <h3 class="sectionHeadline">OUR TEAM ON SERVICE</h3>
                    <p class="sectionP">They will have to make the best of things its an uphill climb</p>

                    <div class="row">
                        <div class="col-sm-6 col-md-6 col-lg-3">

                            <figure class="imageSection8">
                                <img class="img img-responsive" src="/front/img/section8-img.png" alt=""/>
                                <div class="imgContent">
                                    <div class="drInfo">
                                        <h4>DR. JOHN FRANCIS</h4>
                                        <p class="sectionP">Veterinary Chief</p>
                                    </div>

                                </div>
                                <div class="doctorNetwork">
                                    <a href="#"><span class="fa fa-twitter"></span></a>
                                    <a href="#"><span class="fa fa-facebook"></span></a>
                                    <a href="#"><span class="fa fa-google-plus"></span></a>
                                    <a href="#"><span class="fa fa-linkedin"></span></a>
                                </div>
                            </figure>

                        </div>

                        <div class="col-sm-6 col-md-6 col-lg-3">
                            <figure class="imageSection8">
                                <img class="img img-responsive" src="/front/img/section8-img.png" alt=""/>
                                <div class="imgContent">
                                    <div class="drInfo">
                                        <h4>DR. ZOYA MERLIN</h4>
                                        <p class="sectionP">Veterinary Physician</p>
                                    </div>

                                </div>
                                <div class="doctorNetwork">
                                    <a href="#"><span class="fa fa-twitter"></span></a>
                                    <a href="#"><span class="fa fa-facebook"></span></a>
                                    <a href="#"><span class="fa fa-google-plus"></span></a>
                                    <a href="#"><span class="fa fa-linkedin"></span></a>
                                </div>
                            </figure>
                        </div>

                        <div class="col-sm-6 col-md-6 col-lg-3">
                            <figure class="imageSection8">
                                <img class="img img-responsive" src="/front/img/section8-img.png" alt=""/>
                                <div class="imgContent">
                                    <div class="drInfo">
                                        <h4>DR. HENDRI WHEIN</h4>
                                        <p class="sectionP">Veterinary Surgeon</p>
                                    </div>

                                </div>
                                <div class="doctorNetwork">
                                    <a href="#"><span class="fa fa-twitter"></span></a>
                                    <a href="#"><span class="fa fa-facebook"></span></a>
                                    <a href="#"><span class="fa fa-google-plus"></span></a>
                                    <a href="#"><span class="fa fa-linkedin"></span></a>
                                </div>
                            </figure>
                        </div>

                        <div class="col-sm-6 col-md-6 col-lg-3">
                            <figure class="imageSection8">
                                <img class="img img-responsive" src="/front/img/section8-img.png" alt=""/>
                                <div class="imgContent">
                                    <div class="drInfo">
                                        <h4>DR. SCARLET WINSON</h4>
                                        <p class="sectionP">Veterinary Examinist</p>
                                    </div>

                                </div>
                                <div class="doctorNetwork">
                                    <a href="#"><span class="fa fa-twitter"></span></a>
                                    <a href="#"><span class="fa fa-facebook"></span></a>
                                    <a href="#"><span class="fa fa-google-plus"></span></a>
                                    <a href="#"><span class="fa fa-linkedin"></span></a>
                                </div>
                            </figure>

                        </div>
                    </div>
            </section>