<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <?php echo $this->headTitle('My Project')->setSeparator(' | '); ?>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- @todo: fill with your company info or remove -->
        <?php echo $this->headMeta(); ?>
        <!-- General CSS -->
        <link rel="apple-touch-icon" href="<?php echo $this->baseUrl('/front/apple-touch-icon.png'); ?>">

        <link rel="stylesheet" href="<?php echo $this->baseUrl('/front/css/bootstrap.css'); ?>">

        <link href='https://fonts.googleapis.com/css?family=Oxygen:400,300,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.theme.min.css">
        <link href="<?php echo $this->baseUrl('/front/css/slider-css.css'); ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl('/front/css/bootstrap-datetimepicker.css'); ?>" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/front/css/main.css'); ?>">

        <link href="<?php echo $this->baseUrl('/front/css/responsive.css'); ?>" rel="stylesheet" type="text/css"/>
        
        <!--        JS-->

        <script src="<?php echo $this->baseUrl('/front/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js'); ?>"></script>
        
        <?php echo $this->headLink(); ?>
        <!-- Theme  CSS -->

        <?php echo $this->headStyle(); ?>

        <?php echo $this->headScript(); ?>
    </head>

    <!-- ======== @Region: body ======== -->
    <body>
     <!-- HEADER START -->
        <header>
            <div class="container clearfix headerMain">
                <section class="headerTop">
                    <!-- MODAL START -->
                    <button type="button" class="btn btn-info btn-lg modalButton" data-toggle="modal" data-target="#myModal"><span class="fa fa-arrow-circle-down"></span></button>
                    <!-- Modal -->
                    <div class="modal fade" id="myModal" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">Hi,Im modal!</h4>
                                </div>
                                <div class="modal-body">
                                    <p>I can be very useful.</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </div>
                            </div>

                        </div>
                    </div>
                    <!-- MODAL STOP -->
                    <span>Leave A Message: </span>
                    <a class="mail" href="mailto:youremailaddress">info@petcare.com</a>
                </section>
                <section class="headerSocial">
                    <a class="twitter" href="#"><span class="fa fa-twitter social"></span></a>
                    <a class="facebook" href="#"><span class="fa fa-facebook social"></span></a>
                    <a class="googlePlus" href="#"><span class="fa fa-google-plus social"></span></a>
                    <a class="dribbble" href="#"><span class="fa fa-dribbble social"></span></a>
                    <a class="linkedIn" href="#"><span class="fa fa-linkedin social"></span></a>
                </section>

            </div>
            <div class="headerMid">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">
                            <article>
                                <img class="img-responsive Logo" src="<?php echo $this->baseUrl('/front/img/Logo.png'); ?>" alt="Logo"/>
                            </article>
                        </div>
                        <div class="col-md-6 location">
                            <div class="row">
                                <div class="col-md-4">
                                    <article>
                                        <div class="media">
                                            <a class="media-left" href="#">
                                                <span class="fa fa-map-marker"></span>
                                            </a>
                                            <div class="media-body">

                                                <p class="media-heading">Our Location</p>
                                                <p>50 - Design Street, Texas</p>
                                            </div>
                                        </div>
                                    </article>
                                </div>

                                <div class="col-md-4">
                                    <article>
                                        <div class="media">
                                            <a class="media-left" href="#">
                                                <span class="fa fa-hourglass-half"></span>
                                            </a>
                                            <div class="media-body">

                                                <p class="media-heading">Mon - Sat</p>
                                                <p>8 am - 10 pm</p>
                                            </div>
                                        </div>
                                    </article>
                                </div>

                                <div class="col-md-4">
                                    <article>
                                        <div class="media">
                                            <a class="media-left" href="#">
                                                <span class="fa fa-mobile"></span>
                                            </a>
                                            <div class="media-body">

                                                <p class="media-heading">Call Us</p>
                                                <p>+1 (0) 234 56 789</p>
                                            </div>
                                        </div>
                                    </article>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <article>
                                <a class="shoppingCart" href="#"><span class="fa fa-shopping-basket"></span><span class="badge">10</span></a>
                            </article>
                        </div>
                    </div>
                </div>
            </div>

            <!-- BOOTSTRAP NAVIGATION START -->
            <div class="mainNav">
                <div class="container">
                    <nav class="navbar navbar-default">
                        <div class="container-fluid mainNavFluid">
                            <!-- Brand and toggle get grouped for better mobile display -->
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>

                            </div>
                            <?php echo $this->topMenuHtml();?>
                
                            <div class="shoppingCartContent">
                                <table class="table table-responsive tableCart">
                                    <tbody>
                                        <tr> 
                                            <td>
                                                <figure class="cartFigure">
                                                    <a href="#"><img src="/front/img/product-img3.jpg" alt=""/></a>
                                                </figure>
                                            </td>
                                            <td>Pet Food</td> 
                                            <td class="tdPrice">$ 50,00</td> 

                                            <td><a href="/front/#javascript:void(0)" class="remove">Remove</a></td>
                                        </tr> 
                                        <tr> 
                                            <td>
                                                <figure class="cartFigure">
                                                    <a href="#"><img src="/front/img/product-img.jpg" alt=""/></a>
                                                </figure>
                                            </td>
                                            <td>Neck Harness</td> 
                                            <td class="tdPrice">$ 120,00</td> 

                                            <td><a href="/front/#javascript:void(0)" class="remove">Remove</a></td>
                                        </tr> 
                                        <tr> 
                                            <td>
                                                <figure class="cartFigure">
                                                    <a href="#"><img src="" alt=""/></a>
                                                </figure>
                                            </td>
                                            <td>Talking Parrot</td> 
                                            <td class="tdPrice">$ 380,00</td> 

                                            <td><a href="/front/#javascript:void(0)" class="remove">Remove</a></td>
                                        </tr> 
                                    </tbody>
                                    <tfoot>
                                        <tr class="trBuy"> 
                                            <td>TOTAL:</td> 
                                            <td></td> 
                                            <td><button class="btn-default cartButton">BUY</button></td>
                                            <td></td> 
                                        </tr> 
                                    </tfoot>
                                </table>
                            </div>
                        </div><!-- /.container-fluid -->
                    </nav>
                </div>
            </div>
            <!-- BOOTSTRAP NAVIGATION STOP -->
        </header>
 

        <!-- dovde ide telo layout-a -->
        <?php echo $this->layout()->content; ?>
        <!-- FOOTER -->

        <!-- ======== @Region: #footer ======== -->

<footer class="footerBody">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                        <h4 class="text-uppercase text-left footerh4padd">about us</h4>
                        <p class="text-left">Hello we are Comre. We are here to provide you the best offers through our coupons. offers through our coupons. Hello we are company.Hello we are company.</p>
                        
<!--                        <p class="text-left marginator">offers through our coupons. Hello we are company.</p>-->
                        
                       <?php
                            $this->footerdata();
                       ?>
                        
                        

                    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                        <div class="footerSubscriber">
                            <h4 class="text-uppercase">subscrive to mail!</h4>
                            <p class="text-left">Get our Daily email newsletter with </p>
                            <p class="text-left marginator">pecial Services, Updates, Offers and more!</p>

                            <div class="input-group">
                                <input type="text" class="form-control footerInput" placeholder="EMAIL ADRESS">
                                <span class="input-group-btn">
                                    <button class="btn btn-default footerButton" type="button">SIGN UP</button>
                                </span>
                            </div><!-- /input-group -->

                        </div>
                        <div class="footerSocial">
                            <a class="aSocial" href="#"><span class="fa fa-facebook"></span></a>
                            <a class="aSocial" href="#"><span class="fa fa-google-plus"></span></a>
                            <a class="aSocial" href="#"><span class="fa fa-tumblr"></span></a>
                            <a class="aSocial" href="#"><span class="fa fa-dribbble"></span></a>
                            <a class="aSocial" href="#"><span class="fa fa-linkedin"></span></a>
                            <a class="aSocial" href="#"><span class="fa fa-twitter"></span></a>
                        </div>
                    </div>


                </div>
            </div>
        
        <section class="footerBottom">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-6">
                        <ul class="list-unstyled list-inline faqList">
                            <li><a href="#">FAQ</a><span>|</span></li>
                            <li><a href="#">NEWS</a><span>|</span></li>
                            <li><a href="#">CLIENT  SUPPORT</a></li>
                        </ul>
                    </div>

                    <div class="col-xs-12 col-sm-6 copyright">
                        <span>copyrights © 2015 Company. All rights reserved</span>
                    </div>
                </div>
            </div>
        </section>
            <section class="development ">
                <p class="text-center" style="color: #fff;">Ovaj projekat je realizovan u okviru <a href="http://school.cubes.rs">CUBES SCHOOL</a>. Projekat realizovali: FRONTEND <a href="#">Nikita Abrashkin</a> & <a href="#">Ivan Markovic</a>, BACKEND </p>
            </section>
        </footer>

        <!--Scripts -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.js"></script>
        <script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl('/front/js/vendor/jquery-1.11.2.js'); ?>"><\/script>')</script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js"></script>


        <script src="<?php echo $this->baseUrl('/front/js/vendor/bootstrap.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/front/js/vendor/jquery.nstSlider.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl('/front/js/vendor/bootstrap-datetimepicker.js'); ?>" type="text/javascript"></script>
        <script type="text/javascript">

            $('.form_date').datetimepicker({
                weekStart: 1,
                todayBtn: 1,
                autoclose: 1,
                todayHighlight: 1,
                startView: 2,
                minView: 2,
                forceParse: 0
            });
            $('.form_time').datetimepicker({
                language: 'fr',
                weekStart: 1,
                todayBtn: 1,
                autoclose: 1,
                todayHighlight: 1,
                startView: 1,
                minView: 0,
                maxView: 1,
                forceParse: 0
            });
        </script>
        <script src="/front/js/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function (b, o, i, l, e, r) {
                b.GoogleAnalyticsObject = l;
                b[l] || (b[l] =
                        function () {
                            (b[l].q = b[l].q || []).push(arguments)
                        });
                b[l].l = +new Date;
                e = o.createElement(i);
                r = o.getElementsByTagName(i)[0];
                e.src = '//www.google-analytics.com/analytics.js';
                r.parentNode.insertBefore(e, r)
            }(window, document, 'script', 'ga'));
            ga('create', 'UA-XXXXX-X', 'auto');
            ga('send', 'pageview');
            </script>
        <?php echo $this->inlineScript(); ?>
    </body>

</html>
