<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <?php echo $this->headTitle('My Project')->setSeparator(' | '); ?>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- @todo: fill with your company info or remove -->
        <?php echo $this->headMeta(); ?>
        <!-- General CSS -->
        <link rel="apple-touch-icon" href="<?php echo $this->baseUrl('/front/apple-touch-icon.png'); ?>">

        <link rel="stylesheet" href="<?php echo $this->baseUrl('/front/css/bootstrap.css'); ?>">

        <link href='https://fonts.googleapis.com/css?family=Oxygen:400,300,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.theme.min.css">
        <link href="<?php echo $this->baseUrl('/front/css/slider-css.css'); ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl('/front/css/bootstrap-datetimepicker.css'); ?>" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/front/css/main.css'); ?>">

        <link href="<?php echo $this->baseUrl('/front/css/responsive.css'); ?>" rel="stylesheet" type="text/css"/>

        <!--        JS-->

        <script src="<?php echo $this->baseUrl('/front/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js'); ?>"></script>

        <?php echo $this->headLink(); ?>
        <!-- Theme  CSS -->

        <?php echo $this->headStyle(); ?>

        <?php echo $this->headScript(); ?>
    </head>

    <!-- ======== @Region: body ======== -->
    <body>
        <!-- HEADER START -->
        <header>
            
           <?php echo $this->headerdata(); ?>
           

            <!-- BOOTSTRAP NAVIGATION START -->
            <div class="mainNav">
                <div class="container">
                    <nav class="navbar navbar-default">
                        <div class="container-fluid mainNavFluid">
                            <!-- Brand and toggle get grouped for better mobile display -->
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>

                            </div>
                            <?php echo $this->topMenuHtml(); ?>

<!--                            <div class="shoppingCartContent">
                                <table class="table table-responsive tableCart">
                                    <tbody>
                                        <tr> 
                                            <td>
                                                <figure class="cartFigure">
                                                    <a href="#"><img src="/front/img/product-img3.jpg" alt=""/></a>
                                                </figure>
                                            </td>
                                            <td>Pet Food</td> 
                                            <td class="tdPrice">$ 50,00</td> 

                                            <td><a href="/front/#javascript:void(0)" class="remove">Remove</a></td>
                                        </tr> 
                                        <tr> 
                                            <td>
                                                <figure class="cartFigure">
                                                    <a href="#"><img src="/front/img/product-img.jpg" alt=""/></a>
                                                </figure>
                                            </td>
                                            <td>Neck Harness</td> 
                                            <td class="tdPrice">$ 120,00</td> 

                                            <td><a href="/front/#javascript:void(0)" class="remove">Remove</a></td>
                                        </tr> 
                                        <tr> 
                                            <td>
                                                <figure class="cartFigure">
                                                    <a href="#"><img src="" alt=""/></a>
                                                </figure>
                                            </td>
                                            <td>Talking Parrot</td> 
                                            <td class="tdPrice">$ 380,00</td> 

                                            <td><a href="/front/#javascript:void(0)" class="remove">Remove</a></td>
                                        </tr> 
                                    </tbody>
                                    <tfoot>
                                        <tr class="trBuy"> 
                                            <td>TOTAL:</td> 
                                            <td></td> 
                                            <td><button class="btn-default cartButton">BUY</button></td>
                                            <td></td> 
                                        </tr> 
                                    </tfoot>
                                </table>
                            </div>-->
                        </div><!-- /.container-fluid -->
                    </nav>
                </div>
            </div>
            <!-- BOOTSTRAP NAVIGATION STOP -->
        </header>
        
        <main>


        <!-- dovde ide telo layout-a -->
        <?php echo $this->layout()->content; ?>
        <!-- FOOTER -->
        </main>
        <!-- ======== @Region: #footer ======== -->

        <footer class="footerBody">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">


<!--                        <p class="text-left marginator">offers through our coupons. Hello we are company.</p>-->

                        <?php
                        $this->footerdata();
                        ?>

                    </div>
                </div>

<!--                <section class="footerBottom">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12 col-sm-6">
                                <ul class="list-unstyled list-inline faqList">
                                    <li><a href="#">FAQ</a><span>|</span></li>
                                    <li><a href="#">NEWS</a><span>|</span></li>
                                    <li><a href="#">CLIENT  SUPPORT</a></li>
                                </ul>
                            </div>

                            <div class="col-xs-12 col-sm-6 copyright">
                                <span>copyrights © 2015 Company. All rights reserved</span>
                            </div>
                        </div>
                    </div>
            </div>-->
        </section>
        <section class="development ">
            <p class="text-center" style="color: #fff;">Ovaj projekat je realizovan u okviru <a href="http://school.cubes.rs">CUBES SCHOOL</a>.</p>
            <p class="text-center" style="color: #fff;">   Projekat realizovali: FRONTEND <a href="https://rs.linkedin.com/in/nikita-abrashkin-760058115/de" target="_blank">Nikita Abrashkin</a> & <a href="#">Ivan Markovic</a>, BACKEND  <a href="https://www.linkedin.com/in/natasa-lukic-930081123" target="_blank">Nataša Lukić</a></p>
        </section>
    </footer>

    <!--Scripts -->
   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.js"></script>
    <script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl('/front/js/vendor/jquery-1.11.2.js'); ?>"><\/script>')</script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js"></script>

    
    <script src="<?php echo $this->baseUrl('/front/js/vendor/bootstrap.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/front/js/vendor/jquery.nstSlider.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl('/front/js/vendor/bootstrap-datetimepicker.js'); ?>" type="text/javascript"></script>
    <script type="text/javascript">

        $('.form_date').datetimepicker({
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            minView: 2,
            forceParse: 0
        });
        $('.form_time').datetimepicker({
            language: 'fr',
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 1,
            minView: 0,
            maxView: 1,
            forceParse: 0
        });
    </script>
    <script src="/front/js/main.js"></script>

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
        (function (b, o, i, l, e, r) {
            b.GoogleAnalyticsObject = l;
            b[l] || (b[l] =
                    function () {
                        (b[l].q = b[l].q || []).push(arguments)
                    });
            b[l].l = +new Date;
            e = o.createElement(i);
            r = o.getElementsByTagName(i)[0];
            e.src = '//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e, r)
        }(window, document, 'script', 'ga'));
        ga('create', 'UA-XXXXX-X', 'auto');
        ga('send', 'pageview');
    </script>
    <?php echo $this->inlineScript(); ?>
</body>

</html>
