<?php
$this->headTitle('Producers - New Producer');
$form = $this->form;
//
$form->setElementDecorators(array('ViewHelper'));
?>


<div class="page-header">
    <h1>Producers <small>New Producer</small></h1>
</div>

<div class="row">
    <div class="col-lg-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages); ?>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right" >
                <div class="btn-group" role="group" aria-label="...">
                    <a  href="<?php echo $this->url(array('controller' => 'admin_producers', 'action' => 'index'), 'default', true); ?>" type="button" 
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-arrow-left"></i>Back to all producers</a>

                </div>  
            </div>
            <div class="panel-body">

                <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                    <input type="hidden" name="task" value="save">
                    <fieldset>

                        <!-- Form Name -->
                        <legend>New Producer</legend>

                        <!-- Text input-->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="name">Name</label>  
                                <div class="col-md-4">
                                    <?php
                                    echo $form->getElement('name')->setAttribs(array(
                                        'class' => 'form-control input-md',
                                        'placeholder' => "enter producer\'s name",
                                        'id' => 'name',
                                        'required' => 'required'
                                    ));
                                    ?>

                                    <span class="help-block">min 3 max 25 characters</span>  
                                </div>

                                <div class="col-md-4">
                                    <?php if ($form->getElement('name')->hasErrors()) { ?>
                                        <div class="has-error">
                                            <?php foreach ($form->getElement('name')->getMessages() as $message) { ?>
                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>

                            </div>

                              <!-- Text input-->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="address">Address</label>  
                                <div class="col-md-4">
                                    <?php
                                    echo $form->getElement('address')->setAttribs(array(
                                        'class' => 'form-control input-md',
                                        'placeholder' => "enter producer\'s address",
                                        'id' => 'address',
                                        'required' => 'required'
                                    ));
                                    ?>

                                    <span class="help-block">min 3 max 25 characters</span>  
                                </div>

                                <div class="col-md-4">
                                    <?php if ($form->getElement('address')->hasErrors()) { ?>
                                        <div class="has-error">
                                            <?php foreach ($form->getElement('address')->getMessages() as $message) { ?>
                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>

                            </div>

                           

                            <!-- Textarea -->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="about">Description</label>
                                <div class="col-md-4"> 

                                    <?php
                                    echo $form->getElement('about')->setAttribs(array(
                                        'class' => 'form-control',
                                        'id' => 'about',
                                        'rows' => 12
                                    ));
                                    ?>

                                </div>
                                <div class="col-md-4">
                                    <?php if ($form->getElement('about')->hasErrors()) { ?>
                                        <div class="has-error">
                                            <?php foreach ($form->getElement('about')->getMessages() as $message) { ?>
                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                            
                                <!-- Image -->
                        
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="producer_photo">Photo</label>
                            <div class="col-md-4"> 
                                <div>
                                    <a href="#" class="thumbnail">
                                        <img src="<?php echo $this->producerImgUrl($this->producer);?>">
                                    </a>
                                    
                                </div>
                                <input type="file" name="producer_photo" id="producer_photo" class="form-control  input-md">
                                <span class="help-block">Change Photo</span>
                                
                            </div>
                            <div class="col-md-4">
                                 <?php if ($form->getElement('producer_photo')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('producer_photo')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>

                        <!-- Button (Double) -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="new_producer_cancel"></label>
                            <div class="col-md-4 text-right">
                                <a 
                                    href ="<?php echo $this->url(array('controller'=> 'admin_producers', 'action'=> 'index'), 'default', true)?>"
                                    id="new_producer_cancel" name="new_producer_cancel" class="btn btn-default">Cancel</a>
                                <button type="submit" id="new_producer_submit" name="new_producer_submit" class="btn btn-success">Save</button>
                            </div>

                        </div>

                    </fieldset>
                </form>



            </div>
        </div>
    </div>
</div>