<?php
$this->headTitle('Products - New Product');
$form = $this->form;
//
$form->setElementDecorators(array('ViewHelper'));
?>


<div class="page-header">
    <h1>Products <small>New Product</small></h1>
</div>

<div class="row">
    <div class="col-lg-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages); ?>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right" >
                <div class="btn-group" role="group" aria-label="...">
                    <a  href="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'index'), 'default', true); ?>" type="button" 
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-arrow-left"></i>Back to all products</a>

                </div>  
            </div>
            <div class="panel-body">

                <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                    <input type="hidden" name="task" value="save">
                    <fieldset>

                        <!-- Form Name -->
                        <legend>New Product</legend>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="title">Product's Name</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('title')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => "enter product\'s name",
                                    'id' => 'title',
                                    'required' => 'required'
                                ));
                                ?>

                                <span class="help-block">min 3 max 25 characters</span>  
                            </div>

                            <div class="col-md-4">
                                <?php if ($form->getElement('title')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('title')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>

                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="price">Price</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('price')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter product\'s  price',
                                    'id' => 'price',
                                ));
                                ?>

                                
                                <span class="help-block">min 3 max 25 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('price')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('price')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="category_id">Category</label>  
                            <div class="col-md-4">
                                
                                 <?php
                                echo $form->getElement('category_id')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter product\'s  category',
                                    'id' => 'category_id',
                                    'required' => 'required'
                                ));
                                ?>
                                 
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('category_id')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('category_id')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                                
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="about">Description</label>  
                            <div class="col-md-4">
                                
                                 <?php
                                echo $form->getElement('about')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'about product',
                                    'id' => 'about',
                                    
                                ));
                                ?>
                                
                                <span class="help-block">ex. "senior  web developer"</span>  
                            </div>
                            <div class="col-md-4">
                                   <?php if ($form->getElement('about')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('about')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                            </div>
                        </div>

                       
                          <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="producer_id">Producer</label>  
                            <div class="col-md-4">
                                
                                 <?php
                                echo $form->getElement('producer_id')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter product\'s  producer',
                                    'id' => 'producer_id',
                                    'required' => 'required'
                                ));
                                ?>
                                 
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('producer_id')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('producer_id')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                                
                            </div>
                        </div>
                        
                          
                          <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="pet_id">Category</label>  
                            <div class="col-md-4">
                                
                                 <?php
                                echo $form->getElement('pet_id')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter pet',
                                    'id' => 'pet_id',
                                    'required' => 'required'
                                ));
                                ?>
                                 
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('pet_id')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('pet_id')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                                
                            </div>
                        </div>
                        <!-- Image -->
                        
                          <div class="form-group">
                            <label class="col-md-4 control-label" for="product_photo">Photo</label>
                            <div class="col-md-4"> 
                                <div>
                                    <a href="#" class="thumbnail">
                                        <img src="<?php echo $this->productImgUrl($this->product);?>">
                                    </a>
                                    
                                </div>
                                <input type="file" name="product_photo" id="product_photo" class="form-control  input-md">
                                <span class="help-block">Change Photo</span>
                                
                            </div>
                            <div class="col-md-4">
                                 <?php if ($form->getElement('product_photo')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('product_photo')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                     
                        
                        
                        <!-- Button (Double) -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="new_product_cancel"></label>
                            <div class="col-md-4 text-right">
                                <a 
                                    href ="<?php echo $this->url(array('controller'=> 'admin_products', 'action'=> 'index'), 'default', true)?>"
                                    id="new_product_cancel" name="new_product_cancel" class="btn btn-default">Cancel</a>
                                <button type="submit" id="new_product_submit" name="new_product_submit" class="btn btn-success">Save</button>
                            </div>

                        </div>

                    </fieldset>
                </form>



            </div>
        </div>
    </div>
</div>