<?php
$this->headTitle('Products - New Product');
$form = $this->form;
//
$form->setElementDecorators(array('ViewHelper'));
?>


<div class="page-header">
    <h1>Products <small>New Product</small></h1>
</div>

<div class="row">
    <div class="col-lg-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages); ?>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right" >
                <div class="btn-group" role="group" aria-label="...">
                    <a  href="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'index'), 'default', true); ?>" type="button" 
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-arrow-left"></i>Back to all products</a>

                </div>  
            </div>
            <div class="panel-body">

                <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                    <input type="hidden" name="task" value="save">
                    <fieldset>

                        <!-- Form Name -->
                        <legend>New Product</legend>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="title">Product's Name</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('first_name')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => "enter product\'s name",
                                    'id' => 'title',
                                    'required' => 'required'
                                ));
                                ?>

                                <span class="help-block">min 3 max 25 characters</span>  
                            </div>

                            <div class="col-md-4">
                                <?php if ($form->getElement('title')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('title')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>

                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="price">Price</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('price')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter product\'s  price',
                                    'id' => 'price',
                                ));
                                ?>

                                
                                <span class="help-block">min 3 max 25 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('price')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('price')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="email">Email</label>  
                            <div class="col-md-4">
                                
                                 <?php
                                echo $form->getElement('email')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter product\'s  email',
                                    'id' => 'email',
                                    'required' => 'required'
                                ));
                                ?>
                                
                                <span class="help-block">username@domain</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('email')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('email')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                                
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="work_title">Work Title</label>  
                            <div class="col-md-4">
                                
                                 <?php
                                echo $form->getElement('work_title')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter product',
                                    'id' => 'work_title',
                                    
                                ));
                                ?>
                                
                                <span class="help-block">ex. "senior  web developer"</span>  
                            </div>
                            <div class="col-md-4">
                                   <?php if ($form->getElement('work_title')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('work_title')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                            </div>
                        </div>

                        <!-- Textarea -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="resume">Resume</label>
                            <div class="col-md-4"> 
                                
                                 <?php
                                echo $form->getElement('resume')->setAttribs(array(
                                    'class' => 'form-control',
                                    'id' => 'resume',
                                    'rows' => 12
                                    
                                ));
                                ?>
                                
                            </div>
                            <div class="col-md-4">
                                 <?php if ($form->getElement('resume')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('resume')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                        
                        
                        <!-- Image -->
                        
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="product_photo">Photo</label>
                            <div class="col-md-4"> 
                                
                                <input type="file" name="product_photo" id="product_photo" class="form-control  input-md">
                                
                            </div>
                            <div class="col-md-4">
                                 <?php if ($form->getElement('product_photo')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('product_photo')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="twitter">Twitter</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('twitter')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter twitter link',
                                    'id' => 'twitter',
                                ));
                                ?>

                                
                                <span class="help-block">min 3 max 25 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('twitter')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('twitter')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="facebook">Facebook</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('facebook')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter facebook link',
                                    'id' => 'facebook',
                                ));
                                ?>

                                
                                <span class="help-block">min 3 max 25 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('facebook')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('facebook')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="google_plus">Google Plus</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('google_plus')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter google_plus link',
                                    'id' => 'google_plus',
                                ));
                                ?>

                                
                                <span class="help-block">min 3 max 25 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('google_plus')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('google_plus')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="linkedin">Linkedin</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('linkedin')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter linkedin link',
                                    'id' => 'linkedin',
                                ));
                                ?>

                                
                                <span class="help-block">min 3 max 25 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('linkedin')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('linkedin')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                                
                            </div>
                        </div>
                        
                        
                        <!-- Button (Double) -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="new_product_cancel"></label>
                            <div class="col-md-4 text-right">
                                <a 
                                    href ="<?php echo $this->url(array('controller'=> 'admin_products', 'action'=> 'index'), 'default', true)?>"
                                    id="new_product_cancel" name="new_product_cancel" class="btn btn-default">Cancel</a>
                                <button type="submit" id="new_product_submit" name="new_product_submit" class="btn btn-success">Save</button>
                            </div>

                        </div>

                    </fieldset>
                </form>



            </div>
        </div>
    </div>
</div>