
<?php
$this->headTitle('Products');
?>


<div class="page-header">

    <div class="row">
        <div class="col-lg-12">
            <?php echo $this->systemMessagesHtml($this->systemMessages); ?>
        </div>
    </div>

    <h1>Products</h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right" >
                <div class="btn-group" role="group" aria-label="...">
                    <button data-action="save-order" 
                            class="btn btn-success" 
                            style="display: none;"><i class="glyphicon glyphicon-save"></i>Save Order</button>

                    <button data-action="toggle-sort" class="btn btn-default" ><i class="glyphicon glyphicon-list"></i>Change Order</button>
                    <a  href="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'add'), 'default', true); ?>" type="button" 
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-plus"></i>Add product</a>

                </div>  
            </div>
            <div class="panel-body">

                <table id="rows-table" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th></th>
                            <th class="text-center">Img</th>
                            <th class="text-center">Status</th>
                            <th>Name</th>
                            <th>Price</th>
                            <th>Producer</th>
                            <th>Category</th>
                            <th>Pet-Category</th>
                            <th class="text-center">#</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->products as $product) {
                            if ($product['status'] == Application_Model_DbTable_CmsMembers::STATUS_DISABLED) {
                                ?>

                                <tr data-product-id="<?php echo $this->escape($product['id']); ?>" class="danger">
                                    <td class="text-center"><i data-action="sort" class="glyphicon glyphicon-list" style="display: none; cursor:pointer;"></i></td>
                                    <td class="text-center"><img style="max-height: 24px;" src="<?php echo $this->productImgUrl($product); ?>"></td>
                                    <td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
                                    <td><?php echo $this->escape($product['title']); ?></td>
                                    <td><?php echo $this->escape($product['price']); ?></td>
                                    <td><?php echo $this->escape($product['producer_id']); ?></td>
                                    <td><?php echo $this->escape($product['category_id']); ?></td>
                                    <td><?php echo $this->escape($product['pet_id']); ?></td>
                                    <td class="text-center">
                                        <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                            <a 
                                                href="<?php echo $this->productUrl($product); ?>" 
                                                target="_blank"
                                                type="button" class="btn btn-default" title="preview"><i class="glyphicon glyphicon-eye-open"></i></a>
                                            <a 
                                                href="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'edit', 'id' => $product['id']), 'default', true); ?>" 
                                                type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                            <button data-productName="<?php echo $this->escape($product['title']);?>" data-product-id="<?php echo $this->escape($product['id']); ?>" data-action="enable" type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
                                            <button data-productName="<?php echo $this->escape($product['title']); ?>" data-product-id="<?php echo $this->escape($product['id']); ?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
                                        </div>
                                    </td>
                                </tr>
                                <?php
                            } else {
                                ?>
                                <tr data-product-id="<?php echo $this->escape($product['id']); ?>">
                                    <td class="text-center"><i data-action="sort" class="glyphicon glyphicon-list" style="display: none; cursor:pointer;"></i></td>
                                    <td class="text-center"><img style="max-height: 24px;" src="<?php echo $this->productImgUrl($product); ?>"></td>
                                    <td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
                                    <td><?php echo $this->escape($product['title']); ?></td>
                                    <td><?php echo $this->escape($product['price']); ?></td>
                                    <td><?php echo $this->escape($product['producer_id']); ?></td>
                                    <td><?php echo $this->escape($product['category_id']); ?></td>
                                    <td><?php echo $this->escape($product['pet_id']); ?></td>
                                    <td class="text-center">
                                        <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                            <a 
                                                href="<?php echo $this->productUrl($product); ?>" 
                                                target="_blank"
                                                type="button" class="btn btn-default" title="preview"><i class="glyphicon glyphicon-eye-open"></i></a>
                                            <a 
                                                href="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'edit', 'id' => $product['id']), 'default', true); ?>"
                                                type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                            <button data-productName="<?php echo $this->escape($product['title']); ?>" data-product-id="<?php echo $this->escape($product['id']); ?>" data-action="disable" type="button" class="btn btn-default" title="disable"><i class="glyphicon glyphicon-remove"></i></button>
                                            <button data-productName="<?php echo $this->escape($product['title']); ?>" data-product-id="<?php echo $this->escape($product['id']); ?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
                                        </div>
                                    </td>
                                </tr>

                                <?php
                            }
                            ?> 


                            <?php
                        }
                        ?>

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

<!-- /.modal-content je po defaultu sakriven MODAL DIALOG-->
<form method="post" action="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'delete'), "default", true); ?>" id="delete-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="delete">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Delete product</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete product: <span class="osoba" class="btn btn-tumblr"></span></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i>Delete</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<!-- /.modal-content je po defaultu sakriven MODAL DIALOG-->
<form method="post" action="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'disable'), "default", true); ?>" id="disable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="disable">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Disable product</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to disable product: <span class="osoba" class="btn btn-tumblr"></span></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i>Disable</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<!-- /.modal-content je po defaultu sakriven MODAL DIALOG-->
<form method="post" action="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'enable'), "default", true); ?>" id="enable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="enable">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Enable product</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to enable product: <span class="osoba" class="btn btn-tumblr"></span></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"></i>Enable</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form><!-- /.modal -->



<form method="post" action="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'updateorder'), "default", true); ?>" style="display: none;" id="save-order-form">

    <input type="hidden" name="task" value="saveOrder">
    <input type="hidden" name="sorted_ids" value="">


</form>

<?php
//dodatni css na nasu stranicu
$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.css'));

$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.js'));
?>



<script>
<?php $this->inlineScript()->captureStart(); ?>

    $('#rows-table').on('click', '[data-action="delete"]', function (e) {
        e.preventDefault();
        e.stopPropagation();


        //calculate target element
        var target = $(this).is('[data-action="delete"]') ? $(this) : $(this).closest('[data-action="delete"]');


        //verzija preko attr fje
        //var productId = target.attr('data-product-id'); //ovde pun naziv sa data

        //verzija preko datat fje
        var productId = target.data('product-id');//ovde ime bez data


        //var productName = target.attr('data-product-id');
        //alert(productId);
        //set value for input field with name "id"


        $('#delete-warning-dialog').find('[name="id"]').val(productId);

        $('#delete-warning-dialog').modal('show');


        var productData = target.attr('data-productName');
        $('.osoba').text(productData);


    });

    $('#rows-table').on('click', '[data-action="disable"]', function (e) {
        e.preventDefault();
        e.stopPropagation();


        //calculate target element
        var target = $(this).is('[data-action="disable"]') ? $(this) : $(this).closest('[data-action="disable"]');

        var productId = target.attr('data-product-id');

        //verzija preko datat fje
        //var productId =target.data('productId');
        //var productName = target.attr('data-product-id');
        //alert(productId);
        //set value for input field with name "id"
        $('#disable-warning-dialog').find('[name="id"]').val(productId);

        $('#disable-warning-dialog').modal('show');

        var productData = target.attr('data-productName');
        $('.osoba').text(productData);

    });

    $('#rows-table').on('click', '[data-action="enable"]', function (e) {
        e.preventDefault();
        e.stopPropagation();


        //calculate target element
        var target = $(this).is('[data-action="enable"]') ? $(this) : $(this).closest('[data-action="enable"]');

        var productId = target.attr('data-product-id');

        //verzija preko datat fje
        //var productId =target.data('productId');
        //var productName = target.attr('data-product-id');
        //alert(productId);
        //set value for input field with name "id"
        $('#enable-warning-dialog').find('[name="id"]').val(productId);

        $('#enable-warning-dialog').modal('show');

        var productData = target.attr('data-productName');
        $('.osoba').text(productData);

    });



    //SORTIRANJE
    $('[data-action="toggle-sort"]').on('click', function (e) {

        e.preventDefault();
        e.stopPropagation();

        var target = $(this).is('[data-action="toggle-sort"]') ? $(this) : $(this).closest('[data-action="toggle-sort"]');

        var sortableTbody = $('#rows-table > tbody');


        if (target.hasClass('active')) {


            target.removeClass('active');
            target.html('<i class="glyphicon glyphicon-list"></i> Change Order');



            //destroy sortable functionallity
            sortableTbody.sortable('destroy');

            //restore old html body
            sortableTbody.html(sortableTbody.data('oldHtml'));

            //hide "handle" for sorting, the icon in first column
            sortableTbody.find('[data-action="sort"]').hide();


            //hide "Save order"
            $('[data-action="save-order"]').hide();

        } else {

            target.addClass('active');

            //method html sets or gets html inside selected element
            target.html('<i class="glyphicon glyphicon-remove"></i> Cancel');

            // save tbody html before sorting under key oldHtml into its data
            sortableTbody.data('oldHtml', sortableTbody.html());

            //initialize sortable functionallity
            sortableTbody.sortable({
                handle: '[data-action="sort"]'

            });

            //sow "handle" for sorting, the icon in first column
            sortableTbody.find('[data-action="sort"]').show();
            //show "Save order"
            $('[data-action="save-order"]').show();
        }

    });


    $('[data-action="save-order"]').on('click', function (e) {

        e.preventDefault();
        e.stopPropagation();

        var productSortedIds = $('#rows-table > tbody').sortable('toArray', {
            attribute: 'data-product-id'
        });



        //select save order form
        var saveOrderForm = $('#save-order-form');

        //find element with name "sorted_ids" in save form and set its value
        //with string wich are sorted ids separated with comma
        //ex. "12, 3, 4..."
        saveOrderForm.find('[name="sorted_ids"]').val(productSortedIds.join(','));

        //trigerujemo submit
        saveOrderForm.trigger('submit');


    });




<?php $this->inlineScript()->captureEnd(); ?>

</script>