 
<?php
$form = $this->form;
$form->setElementDecorators(array('ViewHelper'));

$frontUser = $this->frontUser;
$systemMessages = $this->systemMessages;
?>

 <p class="col-md-6"><?php echo $this->systemMessagesHtml($this->systemMessages); ?></p>
<section class="section4">
   
                <div class="container">
                    <div class="row">
                        <div class="col-md-2">
                            <ul class="nav nav-stacked nav-pills ">
                                <li><a href="#tab1" data-toggle="tab">Moji Podaci</a></li>
                                <li><a href="#tab2" data-toggle="tab">Izmena Podataka</a></li>
                                <li><a href="#tab3" data-toggle="tab">Izmena Lozinke</a></li>
<!--                                <li><a href="#tab4" data-toggle="tab">Moje Poruke 3/8</a></li>-->
<!--                                <li><a href="#tab5" data-toggle="tab">Moje Kupovine</a></li>-->
                            </ul>
                        </div>

                        <div class="col-md-10">
                            <div class="tab-content userTabContent">
                                <!-- TAB 1 -->
                                <div class="tab-pane fade in active" id="tab1">
                                    <h2 class="userInfoHeadline">Moji Podaci</h2>
                                    <div class="media">
                                        <a class="media-left userImage" href="#">
<!--                                            <figure class="userfigureImg">
                                                <img src="img/client2.jpg" class="edia-object img-circle userProfilePic" alt=""/>
                                            </figure>-->

                                        </a>
                                        <div class="media-body userInfo">
                                            <p class="userInfoP"><?php echo $this->escape($frontUser['first_name']. ' ' . $frontUser['last_name']); ?></p>
                                            <p class="userInfoP"><?php echo $this->escape($frontUser['address']);?></p>
                                            <p class="userInfoP"><?php echo $this->escape($frontUser['username']);?></p>
                                            <p class="userInfoP"><?php echo $this->escape($frontUser['telephone']);?></p>
                                            <a href="<?php echo $this->escape($frontUser['email']);?>" class="userInfoEmail"><?php echo $this->escape($frontUser['email']);?></a>
                                        </div>
                                    </div>
                                </div>

                                <!-- TAB 2 -->
                                <div class="tab-pane fade" id="tab2">
                                    <h2 class="userInfoHeadline">Izmena Podataka</h2>
                                    <form data-toggle="validator" role="form" id="mainForm" action="" method="post">
                                        <input type="hidden" name="task" value="update">

                                        <div class="row mainForm">
                                            <div class="col-sm-6">
                                                <!-- Name -->
                                                <div class="form-group">
                                                    <?php 
                                                        echo $form->getElement('first_name')->setAttribs(array(
                                                                'class' => 'contactInputs2 form-control accountName',
                                                                'placeholder' => 'Name',
                                                                'id' => 'first_name',
                                                                'required' => 'required',
                                                                'data-error' => "Invalid name! Maximum 15 characters. Letters only.",
                                                                'pattern' => "^[_A-Z,_a-z]{1,}$",
                                                        ));
                                                        ?>
                                                    <span class="requiredField">*</span>
                                                    <div class="help-block">Maximum 15 characters.</div>
                                                    <div class="help-block with-errors">
                                                        <?php if ($form->getElement('first_name')->hasErrors()) {?>
                                                            <div class="has-error">
                                                                    <?php foreach ($form->getElement('first_name')->getMessages() as $message) {?>
                                                                    <p class="help-block"><?php echo $this->escape($message);?></p>
                                                                    <?php }?>
                                                            </div>
                                                        <?php }?>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-sm-6">
                                                <!-- Surname -->
                                                <div class="form-group">
                                                        <?php 
                                                        echo $form->getElement('last_name')->setAttribs(array(
                                                                'class' => 'contactInputs2 form-control accountSurname',
                                                                'placeholder' => 'Last Name',
                                                                'id' => 'last_name',
                                                                'required' => 'required',
                                                                'data-error' => "Invalid surname! Maximum 15 characters. Letters only.",
                                                                'pattern' => "^[_A-Z,_a-z]{1,}$"
                                                        ));
                                                        ?>
                                                    <span class="requiredField">*</span>
                                                    <div class="help-block">Maximum 15 characters.</div>
                                                    <div class="help-block with-errors">
                                                        <div class="help-block with-errors">
                                                        <?php if ($form->getElement('last_name')->hasErrors()) {?>
                                                        <div class="has-error">
                                                                <?php foreach ($form->getElement('last_name')->getMessages() as $message) {?>
                                                                <p class="help-block"><?php echo $this->escape($message);?></p>
                                                                <?php }?>
                                                        </div>
                                                        <?php }?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <!-- Street Name -->
                                                <div class="form-group">
                                                    <?php 
                                                        echo $form->getElement('address')->setAttribs(array(
                                                                'class' => 'form-control accountStreet contactInputs2',
                                                                'placeholder' => 'Street Name',
                                                                'id' => 'address',
                                                                'required' => 'required',
                                                                'data-error' => "Unesite Vasu ulicu",
                                                        ));
                                                        ?>
                                                    <span class="requiredField">*</span>

                                                    <div class="help-block with-errors">
                                                        <div class="help-block with-errors">
                                                        <?php if ($form->getElement('address')->hasErrors()) {?>
                                                        <div class="has-error">
                                                                <?php foreach ($form->getElement('address')->getMessages() as $message) {?>
                                                                <p class="help-block"><?php echo $this->escape($message);?></p>
                                                                <?php }?>
                                                        </div>
                                                         <?php }?>
                                                    </div>
                                                </div>
                                            </div>
                                           
                                            
                                        </div>
                                       
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <!-- Phone number -->
                                                <div class="form-group">
                                                    
                                                    <?php 
                                                echo $form->getElement('telephone')->setAttribs(array(
                                                        'class' => 'contactInputs2 form-control accountPhone',
                                                        'placeholder' => 'Telephone',
                                                        'id' => 'telephone',
                                                        'required' => 'required',
                                                        'data-error' => "Invalid phone number",
                                                        'pattern' => "[_0-9]{1,}$"
                                                ));
                                                ?>
                                                    <span class="requiredFieldPhone">*</span>
                                                    <div class="help-block with-errors">
                                                        <?php if ($form->getElement('telephone')->hasErrors()) {?>
                                                        <div class="has-error">
                                                                <?php foreach ($form->getElement('telephone')->getMessages() as $message) {?>
                                                                <p class="help-block"><?php echo $this->escape($message);?></p>
                                                                <?php }?>
                                                        </div>
                                                    <?php }?>
                                                    </div>
                                                </div>
                                            </div>
                                       
                                        </div>
                                        
                                        <div class="row">
                                            <div class="col-xs-12 col-sm-6 col-md-6">
                                                <!-- Email address -->
                                                <div class="form-group">
                                                    
                                                    <?php 
                                                        echo $form->getElement('email')->setAttribs(array(
                                                                'class' => 'form-control accountMail contactInputs2',
                                                                'placeholder' => 'Email',
                                                                'id' => 'email',
                                                                'required' => 'required',
                                                                'data-error' => "Email address you entered is invalid",
                                                        ));
                                                        ?>
                                                    <span class="requiredFieldEmail">*</span>
                                                    <div class="help-block with-errors">
                                                        <div class="help-block with-errors">
                                                                <?php if ($form->getElement('email')->hasErrors()) {?>
                                                                <div class="has-error">
                                                                        <?php foreach ($form->getElement('email')->getMessages() as $message) {?>
                                                                        <p class="help-block"><?php echo $this->escape($message);?></p>
                                                                        <?php }?>
                                                                </div>
                                                                <?php }?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
<!--                                            <div class="col-xs-12 col-sm-3 col-md-3">
                                                <div class="form-group">
                                                    <input class="form-control contactInputs2 accountPass" data-error="Please enter your passowrd"  name="pass" placeholder="Password" type="password" id="passwordField" required><span class="requiredFieldPass">*</span>
                                                    <div class="help-block with-errors"></div>

                                                </div>
                                            </div>-->
<!--                                            <div class="col-xs-12 col-sm-3 col-md-3">
                                                <div class="form-group">
                                                    <input class="form-control contactInputs2 accountPass" data-error="Please confirm your passowrd"  name="pass"  placeholder="Confirm Password" type="password" id="confirmPasswordField" data-match="#passwordField" data-match-error="Incorrect Password" required ><span class="requiredFieldPass">*</span>
                                                    <div class="help-block with-errors"></div>

                                                </div>
                                            </div>-->
                                        </div>
                                      


                                        <div class="row">
                                            <div class="form-group dugme col-xs-12 logInDugme">
                                                <button type="submit" class="btn btn-primary buttonSubmit">Prihvati Izmene</button>
                                            </div>
                                        </div>

                                    </div>

                                    </form>              
                                </div>

                                <!-- TAB 3 -->
                                <div class="tab-pane fade" id="tab3">
                                    <h2 class="userInfoHeadline">Izmena Lozinke</h2>
                                    <form data-toggle="validator" role="form" id="mainForm" action="" method="post">
                                        <input type="hidden" name="task" value="newpassword">

                                        <div class="row mainForm text-center">
                                            <div class="col-sm-6">

                                                <div class="row mainForm">
                                                    <div class="col-xs-12 col-sm-12">
                                                        <div class="form-group">
                                                            <input class="form-control contactInputs2 accountPass" data-error="Please enter your passowrd"  name="old_password" placeholder="Old Password" type="password" required><span class="requiredFieldPass">*</span>
                                                            <div class="help-block with-errors"></div>

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row mainForm">
                                                    <div class="col-xs-12 col-sm-12">
                                                        <div class="form-group">
                                                            <input class="form-control contactInputs2 accountPass" data-error="Please enter new password"  name="password" id="passwordField2"  placeholder="New Password" type="password" required ><span class="requiredFieldPass">*</span>
                                                            <div class="help-block with-errors"></div>

                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row mainForm">
                                                    <div class="col-xs-12 col-sm-12">
                                                        <div class="form-group">
                                                            <input class="form-control contactInputs2 accountPass" data-error="Please confirm your new password"  name="password_confirm" data-match="#passwordField2" data-match-error="Incorect Password"  placeholder="Confirm New Password" type="password" required ><span class="requiredFieldPass">*</span>
                                                            <div class="help-block with-errors"></div>

                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="row mainForm">
                                                    <div class="form-group dugme col-xs-12 logInDugme">
                                                        <button type="submit" class="btn btn-primary buttonSubmit text-uppercase">Reset Password</button>
                                                    </div>
                                                </div>
                                            </div>



                                        </div>
                                    </form>
                                </div>
<!--                                <div class="tab-pane fade" id="tab4">
                                    <h2 class="userInfoHeadlineMessage">Moje Poruke</h2><a href="#"><span class="fa fa-trash pull-right"></span></a>
                                    <div class="row message">
                                        <div class="col-md-11">
                                            <span class="userMessage">Vladan.cubes</span><span class="messageDate">13.04.2015</span><span class="messageTime">at 14:05</span><a href="#javascript:void(0)" id="replyMessage"><span class="fa fa-reply messageReply"><i class="reply">Reply</i></span></a>
                                            <p class="inboxMessage">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>

                                        </div>
                                        <div class="col-md-1">
                                            <div class="checkbox">
                                                <label><input type="checkbox" value=""></label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="form-group col-sm-12">
                                                <textarea class="form-control" id="comment" placeholder="Reply to a message"></textarea>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row message">
                                        <div class="col-md-11">
                                            <span class="userMessage">Mire.cubes</span><span class="messageDate">13.04.2015</span><span class="messageTime">at 15:19</span><a href="#javascript:void(0)" id="replyMessage2"><span class="fa fa-reply messageReply"><i class="reply">Reply</i></span></a>
                                            <p class="inboxMessage">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
                                        </div>
                                        <div class="col-md-1">
                                            <div class="checkbox">
                                                <label><input type="checkbox" value=""></label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="form-group col-sm-12">
                                                <textarea class="form-control" id="comment2" placeholder="Reply to a message"></textarea>
                                            </div>
                                        </div>


                                        <div class="ifReplayed">
                                            <div class="row">
                                                <div class="col-md-11">
                                                    <span class="userMessage">Tanja.cubes</span><span class="messageDate">replied 13.04.2015</span><span class="messageTime">at 15:24</span><a href="#javascript:void(0)" id="replyMessage3"><span class="fa fa-reply messageReply"><i class="reply">Reply</i></span></a>
                                                    <p class="inboxMessage">
                                                        It is a long established fact that a reader will be distracted by the readable content of a 
                                                        page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution
                                                        of letters, as opposed to using 'Content here, content here.
                                                    </p>
                                                </div>
                                                <div class="col-md-1">
                                                    <div class="checkbox">
                                                        <label><input type="checkbox" value=""></label>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="form-group col-sm-12">
                                                <textarea class="form-control" id="comment3" placeholder="Reply to a message"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>-->
                                <div class="tab-pane fade" id="tab5">


                                    <!-- Show / Hide rows -->

                                    <table class="table table-responsive">
                                        <thead>
                                            <tr>
                                                <th>Redni Broj</th>
                                                <th>Broj Fakture</th>
                                                <th>Ime Proizvoda</th>
                                                <th>Datum</th>
                                                <th>Vreme</th>
                                                <th>Cena</th>
                                            </tr>

                                        </thead>
                                        <tbody>
                                            <tr class="redovi">
                                                <td>1</td>
                                                <td>1/2016</td>
                                                <td>Artikl 1</td>
                                                <td>1.1.2016</td>
                                                <td>13:01</td>
                                                <td>$50.00</td>
                                            </tr>
                                            <tr class="redovi">
                                                <td>2</td>
                                                <td>2/2016</td>
                                                <td>Artikl 2</td>
                                                <td>2.1.2016</td>
                                                <td>13:02</td>
                                                <td>$150.00</td>
                                            </tr>

                                            <tr class="redovi article1">
                                                <td>3</td>
                                                <td>3/2016</td>
                                                <td>Artikl 3</td>
                                                <td>3.1.2016</td>
                                                <td>13:03</td>
                                                <td>$250.00</td>
                                            </tr>
                                            <tr class="redovi">
                                                <td>1</td>
                                                <td>4/2016</td>
                                                <td>Artikl 4</td>
                                                <td>4.1.2016</td>
                                                <td>15:23</td>
                                                <td>$120.00</td>
                                            </tr>
                                            <tr class="redovi article2">
                                                <td>2</td>
                                                <td>5/2016</td>
                                                <td>Artikl 5</td>
                                                <td>5.1.2016</td>
                                                <td>17:32</td>
                                                <td>$70.00</td>
                                            </tr>
                                            <tr class="redovi hiddenTr">
                                                <td>1</td>
                                                <td>1/2016</td>
                                                <td>Artikl 1</td>
                                                <td>1.1.2016</td>
                                                <td>13:01</td>
                                                <td>$50.00</td>
                                            </tr>
                                            <tr class="redovi hiddenTr">
                                                <td>2</td>
                                                <td>2/2016</td>
                                                <td>Artikl 2</td>
                                                <td>2.1.2016</td>
                                                <td>13:02</td>
                                                <td>$150.00</td>
                                            </tr>

                                            <tr class="redovi article1 hiddenTr">
                                                <td>3</td>
                                                <td>3/2016</td>
                                                <td>Artikl 3</td>
                                                <td>3.1.2016</td>
                                                <td>13:03</td>
                                                <td>$250.00</td>
                                            </tr>
                                            <tr class="redovi hiddenTr">
                                                <td>1</td>
                                                <td>4/2016</td>
                                                <td>Artikl 4</td>
                                                <td>4.1.2016</td>
                                                <td>15:23</td>
                                                <td>$120.00</td>
                                            </tr>
                                            <tr class="redovi article2 hiddenTr">
                                                <td>2</td>
                                                <td>5/2016</td>
                                                <td>Artikl 5</td>
                                                <td>5.1.2016</td>
                                                <td>17:32</td>
                                                <td>$70.00</td>
                                            </tr>

                                        </tbody>
                                    </table>
                                    <div class="container text-center">
                                        <button class="btn btn-default Show_Hide pull-left">Show more</button>
                                    </div>




                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- SECTION USER PANEL STOP -->

<?php

$this->headLink()->appendStylesheet($this->baseUrl('/front/css/user-Panel.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/front/css/responsive.css'));

?>



