 <?php
$this->headTitle('Contacts');

$form = $this->form;
$form->setElementDecorators(array('ViewHelper'));
$systemMessages = $this->systemMessages;
?>


<!-- SECTION 1 SHOP STOP -->

            <div class="locationMap">
                <iframe class="map" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d5659.11172986437!2d20.406708!3d44.830612!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x293617553f646009!2sCubes!5e0!3m2!1sen!2srs!4v1470412218313" width="800" height="470" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>


            <section class="contactSection">

                <h3 class="text-uppercase text-center contactH3">keep in touch</h3>
                <p class="contactP text-center">They will have to make the best of things its an uphill climb</p>
                <div class="container">



                    <div class="row mainForm">
                        <?php if ($systemMessages == 'init') { ?>
                        <form action="" method="POST" id="contact-form" role="form" data-toggle="validator">
                             <input type="hidden" name="task" value="contact">
                        <div class="col-sm-6">
                            <!-- Name -->
                            <div class="form-group">
                                 <?php
                                    echo $form->getElement('name')->setAttribs(array(
                                        'class' => 'form-control contactInputs',
                                        'placeholder' => "Name",
                                        'id' => 'name',
                                        'required' => 'required',
                                        'data-error' => 'Invalid name! Minimum 4 and maximum 15 characters. Letters only.',
                                        'pattern' => '[_A-Z,_a-z]{1,}$',
                                        'data-minlength' => 4,
                                        'data-maxlength' => 15
                                    ));
                                    ?>
                                                     
                                <div class="help-block with-errors">
                                     <?php if ($form->getElement('name')->hasErrors()) { ?>
                                            <div class="has-error">
                                                <?php foreach ($form->getElement('name')->getMessages() as $message) { ?>
                                                    <p class="help-block"><?php echo $this->escape($message); ?></p>
                                                <?php } ?>
                                            </div>
                                        <?php } ?>
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-sm-6">
                            <?php
                                    echo $form->getElement('email')->setAttribs(array(
                                        'class' => 'form-control contactInputs',
                                        'placeholder' => "Email",
                                        'id' => 'email',
                                        'data-error' => 'Email address you entered is invalid.',
                                        'required' => 'required'
                                    ));
                            ?>
                            <div class="help-block with-errors">
                                     <?php if ($form->getElement('email')->hasErrors()) { ?>
                                            <div class="has-error">
                                                <?php foreach ($form->getElement('email')->getMessages() as $message) { ?>
                                                    <p class="help-block"><?php echo $this->escape($message); ?></p>
                                                <?php } ?>
                                            </div>
                                        <?php } ?>
                               </div>
                        </div>
                       <div class="col-sm-12">
                            <!-- Name -->
                            <div class="form-group">
                                 <?php
                                    echo $form->getElement('subject')->setAttribs(array(
                                        'class' => 'form-control contactInputs',
                                        'placeholder' => "Subject",
                                        'type' => "text",
                                        'id' => 'subject',
                                        'required' => 'required',
                                        'data-error' => 'Invalid subject! Minimum 4 and maximum 15 characters. Letters only.',
                                    ));
                                    ?>
                                                     
                                <div class="help-block with-errors">
                                     <?php if ($form->getElement('subject')->hasErrors()) { ?>
                                            <div class="has-error">
                                                <?php foreach ($form->getElement('subject')->getMessages() as $message) { ?>
                                                    <p class="help-block"><?php echo $this->escape($message); ?></p>
                                                <?php } ?>
                                            </div>
                                        <?php } ?>
                                </div>
                            </div>
                        </div>
                   
                   
                        <div class="col-xs-12">
                            <div class="form-group">
                                    <?php
                                    echo $form->getElement('message')->setAttribs(array(
                                        'class' => 'form-control contactInputs',
                                        'placeholder' => "Message",
                                        'id' => 'message',
                                        'required' => 'required',
                                        'rows' => 5
                                    ));
                                    ?>
                                 <div class="help-block with-errors">
                                     <?php if ($form->getElement('message')->hasErrors()) { ?>
                                            <div class="has-error">
                                                <?php foreach ($form->getElement('message')->getMessages() as $message) { ?>
                                                    <p class="help-block"><?php echo $this->escape($message); ?></p>
                                                <?php } ?>
                                            </div>
                                        <?php } ?>
                               </div>
                            </div>
                        </div>
                    
                        <div class="form-group dugme col-xs-12">
                            <input type="submit" value="Send Message" class="btn btn-primary buttonSubmit">
                        </div>
                    
                </form>
                        </div>
                        <?php
                            } else {
                                if ($systemMessages == 'Success'){
                                    echo 'Uspesno poslata poruka';
                                } else {
                                    echo "Doslo je do greske prilikom slanja poruke.";
                                }
                            }
                            ?>
                         </div>
                  
            </section>





