  <!-- SECTION 1 BLOG START -->

            <section class="section1Blog">
                <div class="container">
                    <h3 class="text-uppercase">SHOP - CHEKOUT</h3>
                    <ul class="list-unstyled list-inline ShopList">
                        <li><a href="#">Home</a><span>|</span></li>
                        <li><a href="#">Shop</a><span>|</span></li>
                        <li><a href="#">Place Order</a></li>
                    </ul>
                </div>
            </section>

            <!-- SECTION 1 BLOG STOP -->


            <!-- SECTION 2 BLOG START -->

            <section class="section2Blog">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <h3 class="sectionHeadlineBlog text-uppercase">updates from our shop</h3>
                            <p class="sectionP2">In a freak mishap ranger and its pilot captain william buck rogers are blown</p>
                        </div>

                        <div class="col-md-4">
                            <div class="input-group searchGroup">
                                <input type="text" class="form-control inputSeach" placeholder="Search post here">
                                <span class="input-group-btn">
                                    <button class="btn btn-default buttonSearch" type="button"><span class="fa fa-search"></span></button>
                                </span>
                            </div><!-- /input-group -->
                        </div><!-- /.col-lg-6 -->
                    </div>
                </div>
            </section>
            <!-- SECTION 2 BLOG STOP -->

            <!-- SECTION 3 BLOG START -->


            <section class="section3Blog">
                <div class="container">
                    <div class="row">



                        <div class="col-sx-8 col-sm-12 col-md-8 section12Element">
                            <article class="blogArticle">
                                <figure class="section12Figure">
                                    <img class="img-responsive section12Img" src="/front/img/section12-img.png" alt=""/>
                                    <div class="section12Hover">
                                        <a href="#" class="button readMore12">ADD TO CART</a>                                       
                                    </div>

                                </figure>
                                <div class="underContent2">
                                    <div class="dateTime">
                                        <p class="monthP">SEP</p>
                                        <p><span class="date">28</span></p>
                                    </div>

                                    <a href="#"> <span class="fa fa-comment-o comment"><i>17</i></span></a>
                                    <a href="#"> <span class="fa fa-heart-o"><i>13</i></span></a>

                                    <a href="#"> <span class="fa fa-share-alt share pull-right"><i>Share</i></span></a>
                                    <a href="#"> <span class="fa fa-reply share pull-right"><i>Reply</i></span></a>

                                    <div class="innerDiv text-left">
                                        <p class="headP">Special care on Pets by physician</p>
                                        <p class="innerText">
                                            The weather started getting rough the tiny ship was tossed
                                            if not for the courage of the fearless crew
                                            the Minnow would be lost the minnow lost.
                                        </p>
                                    </div>
                                    <div class="admin clearfix">
                                        <p class="spanUser">
                                            <span class="fa fa-user"></span>
                                            Posted by admin
                                        </p>
                                        <p  class="spanTag">
                                            <span class="fa fa-tag"></span>
                                            Pets, Veterinary, Dog
                                        </p> 
                                    </div>
                                </div>
                            </article>

                            <article class="blogArticle">
                                <figure class="section12Figure">
                                    <img class="img-responsive section12Img" src="/front/img/section12-img.png" alt=""/>
                                    <div class="section12Hover">
                                        <a href="#" class="button readMore12">ADD TO CART</a>                                       
                                    </div>

                                </figure>
                                <div class="underContent2">
                                    <div class="dateTime">
                                        <p class="monthP">SEP</p>
                                        <p><span class="date">28</span></p>
                                    </div>

                                    <a href="#"> <span class="fa fa-comment-o comment"><i>17</i></span></a>
                                    <a href="#"> <span class="fa fa-heart-o"><i>13</i></span></a>

                                    <a href="#"> <span class="fa fa-share-alt share pull-right"><i>Share</i></span></a>
                                    <a href="#"> <span class="fa fa-reply share pull-right"><i>Reply</i></span></a>

                                    <div class="innerDiv text-left">
                                        <p class="headP">Special care on Pets by physician</p>
                                        <p class="innerText">
                                            The weather started getting rough the tiny ship was tossed
                                            if not for the courage of the fearless crew
                                            the Minnow would be lost the minnow lost.
                                        </p>
                                    </div>
                                    <div class="admin clearfix">
                                        <p class="spanUser">
                                            <span class="fa fa-user"></span>
                                            Posted by admin
                                        </p>
                                        <p  class="spanTag">
                                            <span class="fa fa-tag"></span>
                                            Pets, Veterinary, Dog
                                        </p> 
                                    </div>
                                </div>
                            </article>

                            <article class="blogArticle">
                                <figure class="section12Figure">
                                    <img class="img-responsive section12Img" src="/front/img/section12-img.png" alt=""/>
                                    <div class="section12Hover">
                                        <a href="#" class="button readMore12">ADD TO CART</a>                                       
                                    </div>

                                </figure>
                                <div class="underContent2">
                                    <div class="dateTime">
                                        <p class="monthP">SEP</p>
                                        <p><span class="date">28</span></p>
                                    </div>

                                    <a href="#"> <span class="fa fa-comment-o comment"><i>17</i></span></a>
                                    <a href="#"> <span class="fa fa-heart-o"><i>13</i></span></a>

                                    <a href="#"> <span class="fa fa-share-alt share pull-right"><i>Share</i></span></a>
                                    <a href="#"> <span class="fa fa-reply share pull-right"><i>Reply</i></span></a>

                                    <div class="innerDiv text-left">
                                        <p class="headP">Special care on Pets by physician</p>
                                        <p class="innerText">
                                            The weather started getting rough the tiny ship was tossed
                                            if not for the courage of the fearless crew
                                            the Minnow would be lost the minnow lost.
                                        </p>
                                    </div>
                                    <div class="admin clearfix">
                                        <p class="spanUser">
                                            <span class="fa fa-user"></span>
                                            Posted by admin
                                        </p>
                                        <p  class="spanTag">
                                            <span class="fa fa-tag"></span>
                                            Pets, Veterinary, Dog
                                        </p> 
                                    </div>
                                </div>
                            </article>

                            <article class="blogArticle">
                                <figure class="section12Figure">
                                    <img class="img-responsive section12Img" src="/front/img/section12-img.png" alt=""/>
                                    <div class="section12Hover">
                                        <a href="#" class="button readMore12">ADD TO CART</a>                                       
                                    </div>

                                </figure>
                                <div class="underContent2">
                                    <div class="dateTime">
                                        <p class="monthP">SEP</p>
                                        <p><span class="date">28</span></p>
                                    </div>

                                    <a href="#"> <span class="fa fa-comment-o comment"><i>17</i></span></a>
                                    <a href="#"> <span class="fa fa-heart-o"><i>13</i></span></a>

                                    <a href="#"> <span class="fa fa-share-alt share pull-right"><i>Share</i></span></a>
                                    <a href="#"> <span class="fa fa-reply share pull-right"><i>Reply</i></span></a>

                                    <div class="innerDiv text-left">
                                        <p class="headP">Special care on Pets by physician</p>
                                        <p class="innerText">
                                            The weather started getting rough the tiny ship was tossed
                                            if not for the courage of the fearless crew
                                            the Minnow would be lost the minnow lost.
                                        </p>
                                    </div>
                                    <div class="admin clearfix">
                                        <p class="spanUser">
                                            <span class="fa fa-user"></span>
                                            Posted by admin
                                        </p>
                                        <p  class="spanTag">
                                            <span class="fa fa-tag"></span>
                                            Pets, Veterinary, Dog
                                        </p> 
                                    </div>
                                </div>
                            </article>

                            <article class="blogArticle">
                                <figure class="section12Figure">
                                    <img class="img-responsive section12Img" src="/front/img/section12-img.png" alt=""/>
                                    <div class="section12Hover">
                                        <a href="#" class="button readMore12">ADD TO CART</a>                                       
                                    </div>

                                </figure>
                                <div class="underContent2">
                                    <div class="dateTime">
                                        <p class="monthP">SEP</p>
                                        <p><span class="date">28</span></p>
                                    </div>

                                    <a href="#"> <span class="fa fa-comment-o comment"><i>17</i></span></a>
                                    <a href="#"> <span class="fa fa-heart-o"><i>13</i></span></a>

                                    <a href="#"> <span class="fa fa-share-alt share pull-right"><i>Share</i></span></a>
                                    <a href="#"> <span class="fa fa-reply share pull-right"><i>Reply</i></span></a>

                                    <div class="innerDiv text-left">
                                        <p class="headP">Special care on Pets by physician</p>
                                        <p class="innerText">
                                            The weather started getting rough the tiny ship was tossed
                                            if not for the courage of the fearless crew
                                            the Minnow would be lost the minnow lost.
                                        </p>
                                    </div>
                                    <div class="admin clearfix">
                                        <p class="spanUser">
                                            <span class="fa fa-user"></span>
                                            Posted by admin
                                        </p>
                                        <p  class="spanTag">
                                            <span class="fa fa-tag"></span>
                                            Pets, Veterinary, Dog
                                        </p> 
                                    </div>
                                </div>
                            </article>
                        </div>

                        <!-- RIGHT SIDE MENU START -->

                        <div class="col-sx-12 col-sm-12 col-md-4">
                            <h4 class="text-uppercase postH4-1">post categoty</h4>

                            <ul class="list-unstyled sideMenu1">
                                <li><a href="#">Friendly Pets</a></li>
                                <li><a href="#">Exporting Breeds</a></li>
                                <li><a href="#">Henters Pet</a></li>
                                <li><a href="#">All Kind Of Birds</a></li>
                                <li><a href="#">Seller Of The Day</a></li>
                                <li><a href="#">Breeds Of Cats</a></li>

                            </ul>
                        </div>


                        <div class="col-sx-12 col-sm-12 col-md-4">
                            <h4 class="text-uppercase mediaH4">recent post</h4>

                            <!-- SIDE MEDIA 1 -->
                            <div class="media blogMedia">
                                <div class="media-left">
                                    <a href="#">
                                        <img class="media-object" src="/front/img/blogSide-img.png" alt=""/>
                                    </a>
                                </div>
                                <div class="media-body">
                                    <p class="media-heading">Like Robinson Crusoe it is</p>
                                    <p>Primitive as can be</p>
                                    <span class="fa fa-calendar blogSideSpan"><i>Jul 29.2015</i></span>
                                </div>
                            </div>

                            <!-- SIDE MEDIA 2 -->
                            <div class="media blogMedia">
                                <div class="media-left">
                                    <a href="#">
                                        <img class="media-object" src="/front/img/blogSide-img.png" alt=""/>
                                    </a>
                                </div>
                                <div class="media-body">
                                    <p class="media-heading">There's nothing can hold me</p>
                                    <p>when I hold you</p>
                                    <span class="fa fa-calendar blogSideSpan"><i>Aug 22.2015</i></span>
                                </div>
                            </div>

                            <!-- SIDE MEDIA 3 --> 

                            <div class="media blogMedia">
                                <div class="media-left">
                                    <a href="#">
                                        <img class="media-object" src="/front/img/blogSide-img.png" alt=""/>
                                    </a>
                                </div>
                                <div class="media-body">
                                    <p class="media-heading">Five passengers set sail that</p>
                                    <p>day for a three hour</p>
                                    <span class="fa fa-calendar blogSideSpan"><i>Sep 12.2015</i></span>
                                </div>
                            </div>
                        </div>


                        <div class="col-sx-12 col-sm-6 col-md-4">
                            <h4 class="text-uppercase postH4">archives</h4>

                            <ul class="list-unstyled sideMenu1">
                                <li class="archives-li"><a href="#">June 2015</a><a class="pull-right postNumbers text-center" href="#">18</a></li>
                                <li class="archives-li"><a href="#">July 2015</a><a class="pull-right postNumbers text-center" href="#">05</a></li>
                                <li class="archives-li"><a href="#">August 2014</a><a class="pull-right postNumbers text-center" href="#">12</a></li>
                                <li class="archives-li"><a href="#">September 2014</a><a class="pull-right postNumbers text-center" href="#">24</a></li>
                            </ul>
                        </div>

                        <div class="col-sx-12 col-sm-6 col-md-4">
                            <h4 class="text-uppercase postH4popular">popular tags</h4>

                            <a href="#"  class="spanTags">Maltese</a>
                            <a href="#"  class="spanTags">Pit Bull</a>
                            <a href="#"  class="spanTags">Sledge</a>
                            <a href="#"  class="spanTags">Labrador</a>
                            <a href="#"  class="spanTags">Baby Pug</a>
                            <a href="#"  class="spanTags">Birds</a>
                            <a href="#"  class="spanTags">Molosseres</a>
                            <a href="#"  class="spanTags">Coon Hound</a>

                        </div>

                        <!-- RIGHT SIDE MENU STOP -->

                    </div>
                </div>
            </section>

            <!-- PAGINATION -->
            <section class="">
                <div class="container text-center">
                    <ul class="pagination">
                        <li><a class="paginator" href="#"><span class="fa fa-angle-left"></span></a></li>
                        <li><a class="paginator"  href="#">1</a></li>
                        <li><a class="paginator" href="#">2</a></li>
                        <li><a class="paginator" href="#">3</a></li>
                        <li><a class="paginator" href="#"><span class="fa fa-angle-right"></span></a></li>
                    </ul>
                </div>
            </section>

            <!-- SECTION 3 BLOG STOP -->




            <!-- SECTION 4 BLOG START -->

            <section class="section13">
                <div class="container text-center">
                    <div class="row">
                        <div class="col-lg-4 col-md-12">
                            <h3 class="text-uppercase text-center">subscribe our newsletter</h3>
                        </div>

                        <div class="col-lg-3 col-md-5">
                            <div class="form-group">                              
                                <input type="text" class="form-control subscribeInput" id="usr" placeholder="Your Name">
                            </div>
                        </div>

                        <div class="col-lg-3 col-md-5">
                            <div class="form-group">                              
                                <input type="text" class="form-control subscribeInput" id="usr" placeholder="Your E-Mail">
                            </div>
                        </div>

                        <div class="col-lg-2 col-md-2">
                            <div class="form-group">                              
                                <button class="btn btn-default buttonSubscribe">GO</button>
                            </div>
                        </div>

                    </div>


                </div>
            </section>


            <!-- SECTION 4 BLOG STOP -->
